### ISSUE TITLE
Rename project from mdast to remark 🎉

### ISSUE THREAD

**Issue by wooorm** [wooorm/remark#113]
I just received push-access to the `remark` project on npm (by the amazing @phated!), which means, the **mdast** project can step away from the hard-to-pronaunce name towards a much more easily pronounceable **remark**.

I long coveted this name (in lieu of [retext](https://github.com/wooorm/retext)), ever since I forked into mdast [more than a year ago](https://github.com/wooorm/mdast/commit/19585b8e890c0dfdd742019eca5f3fe0a6e9b14f).

Just in time for 3.0.0, but it will mean everything needs to be renamed, from **mdastrc** and **mdastignore** files, to all prefixed plug-ins.

This will also give me the opportunity to separate the AST specification from the API and CLI: **mdast**, similarly to **NLCST** for **retext**, will still be used as a definition for the nodes used by mdast, uhm, I mean, **remark**.

**Comment by wooorm** [comment]
Heads up: @ben-eb, @hughsk, @rsystem-se, @eush77, @anandthakker, @minodisk, @rhysd, @dthree, @ZotPlus, @tmcw, @chcokr, @denysdovhan.

**Comment by chcokr** [comment]
Congrats! Nice name.

**Comment by ben-eb** [comment]
Nice! What do you suggest for plugin renaming?

**Comment by wooorm** [comment]
Thanks @chcokr, @ben-eb.

*  I suggest upping a new major release, released with the new name. In the case of mdast-midas@1.1.0, that would go to remark-midas@2.0.0.

*  Then, create a near-empty project with a README pointing to to remark-midas and a deprecation notice, and publish it at mdast-midas@2.0.0 (yes, a major bump too).

* Use `npm deprecate mdast-midas@2.0.0 'Renamed to remark-midas without API changes'`

That would ensure no users get any deprecation notices normally, but if they are in the process of updating their dependencies, they’ll get one and hopefully rename their dependency. :smile:

I know it’s quite a lot to ask, hope you all don’t mind. Furthermore, I hope the new naming will make the ecosystem better! :tada:

**Comment by eush77** [comment]
> This will also give me the opportunity to separate the AST specification from the API and CLI: mdast, similarly to NLCST for retext, will still be used as a definition for the nodes used by mdast

Does it mean that the preferred name prefix for util packages will be changed to just `mdast-` after rename? And for example [`mdast-util-to-string`](https://www.npmjs.com/package/mdast-util-to-string) will be renamed to `mdast-to-string` to be more in line with [`nlcst-to-string`](https://www.npmjs.com/package/nlcst-to-string)?

**Comment by denysdovhan** [comment]
My congratulations! Cool name!

BTW: If you know there is also [a **remark** slideshow tool](https://github.com/gnab/remark) :smirk:

**Comment by dthree** [comment]
:+1:

**Comment by wooorm** [comment]
@dthree @denysdovhan Yes, thanks! Cool right? And yeah, I saw the project. Luckily I got the access to npm :+1:

@eush77 Yes, that’s the gist of it (see my previous comments for more info). I definitely share your concerns, but I feel that the long run will certainly be worth it. And, importantly, better now than later :ok_hand:

**Comment by rhysd** [comment]
Congrats!  I got it.
