### ISSUE TITLE
How to use .remarkrc

### ISSUE THREAD

**Issue by RichardLitt** [wooorm/remark#116]
I'm sorry that I was unable to find this in the docs, but I am lost as to how to use the .remarkrc. Say I have a plugin I have created, `my-plugin`. I put that into the .remarkrc like so:

```json
{
  "plugins": {
    "my-plugin": {}
  }
}
```

How does remark then find that plugin? Should I add it my `package.json` as well? Do I have to specify it again when I call `mdast()`, and require the plugin in that file so that I can do `mdast().use(myPlugin)`?

**Comment by RichardLitt** [comment]
For reference, here is the repo I am trying to use it in: https://github.com/ipfs/ipfs-readme-standard

**Comment by wooorm** [comment]
In general, you should have the referenced plug-in inside `node_modules/` for it to get loaded properly.

There are also alternative paths being checked, [such as `myplugin.js`, `remark-myplugin`, etcetera](https://github.com/wooorm/remark/blob/5a96751edabf2c0654c33611b87eb047a779ca6d/lib/cli/file-pipeline/configure.js#L113-L127).

Also: the Node API is separate from the CLI, e.g., it doesn’t support `.remarkrc` files, so if you’d like to use a plug-in in node, you must `require()` it and pass it to `.use()`.

Does that help?

**Comment by RichardLitt** [comment]
That does help. I'll see if I can get the plugin working on the CLI. Thank you!

**Comment by wooorm** [comment]
@RichardLitt Could you close this if you figured this out? If not, feel free to keep it open and ping for help :)

**Comment by RichardLitt** [comment]
I have one further question: what do you think the best way would be to enforce a style for multiple repositories? I'm currently implementing something like [standard-readme](https://github.com/zcei/standard-readme) (which I might supplant it with, since that doesn't seem to be going anywhere at the moment). My plan at the moment is to make modules that implement the style I want, and then to make a module with a specified `.remarkrc` that can be used to check other modules as a CLI or linter, which can have their own `.remarkrc` files to specify options. Does that sound smart, to you?

**Comment by wooorm** [comment]
I’m not exactly use whether you are (or are not) planning on creating your own linter (possibly reading `.remarkrc` files too), or whether you’re planning on using just `remark`, with plug-ins, and `remark-lint` (with custom rules?). If the latter, that does sound smart.

Oh: and no, there’s no support for sharable configuration files (e.g., like ESLint), yet.

**Comment by RichardLitt** [comment]
The latter. Cool, good to know about sharable config files as a hurdle. I'll cross that bridge when I come to it. For now, thanks!
