### ISSUE TITLE
qs param mistaken for html char entity

### ISSUE THREAD

**Issue by SpainTrain** [wooorm/remark#117]
In links that contain URLs with certain querystring paramaters, mdast is warning "`Named character references must be terminated by a semicolon`".

#### Fails

```markdown
[![Circle CI](https://circleci.com/gh/home-buddy/homebuddy-webapp/tree/master.svg?style=shield&circle-token=000000a00a0a0000aaa0a00000a000a00000aa00)](https://circleci.com/gh/home-buddy/homebuddy-webapp)
```

This points to char # 100 (`&circle`)

(I sanitized the token)

#### Passes

```markdown
[![codecov.io](http://codecov.io/github/home-buddy/homebuddy-webapp/coverage.svg?branch=master&token=aA0AaAAAaA)](http://codecov.io/github/home-buddy/homebuddy-webapp?branch=master)
```

```markdown
[![Circle CI](https://circleci.com/gh/home-buddy/homebuddy-webapp/tree/master.svg?style=shield)](https://circleci.com/gh/home-buddy/homebuddy-webapp)
```

I tried chasing it down and wasn't clear that it was originating from remark.  LMK if this needs to be filed with an upstream dep.

**Comment by wooorm** [comment]
Thanks for raising the issue, this was wrong. Although some tokens should be seen as entity references without terminating semi-colon (e.g., `&amp`), and `&circ;` is a valid character entity, the latter was not valid when without terminating semi-colon.

Depending on your set-up, throwing `remark` (or `node_modules/`) away, and re=installing, should include this change :smile:

**Comment by SpainTrain** [comment]
looks great, thanks for the quick fix! :heart: 

should have known it was in parse-entities ^_^
