### ISSUE TITLE
Windows fstat Error

### ISSUE THREAD

**Issue by ChristianMurphy** [wooorm/remark#118]
OS: Windows 10
Node: v5.3.0
Plugins: remark-lint, remark-slug, remark-validate-links

``` bash
fs.js:882
   return binding.fstat(fd);
                  ^

 Error: EISDIR: illegal operation on a directory, fstat
     at Error (native)
     at Error (native)
     at Object.fs.fstatSync (fs.js:882:18)
     at Object.<anonymous>
 (C:\...\node_modules\remark\lib\cli\file-set-pipeline\stdin.js:28:17)
     at Module._compile (module.js:398:26)
     at Object.Module._extensions..js (module.js:405:10)
     at Module.load (module.js:344:32)
     at Function.Module._load (module.js:301:12)
     at Module.require (module.js:354:17)
     at require (internal/module.js:12:17)
     at Object.<anonymous> (C:\...\node_modules\remark\lib\cli\file-set-pipeline\index.js:21:13)
```

**Comment by wooorm** [comment]
Thanks for the issue, @ChristianMurphy.

By any chance, were you piping into remark (or not)? And, can you reproduce this when piping (or in that case, do or don’t you get any relating errors)?

P.S. Thanks for GH-119, but I think that disables support for piping from stdin(4) all together. In fact, I was planning on wrapping `fs.fstatSync(0).isFIFO();`  in a `try ... catch` as a solution.

**Comment by ChristianMurphy** [comment]
I was not piping into remark.

I ran
``` bash
remark *.md
```

and
``` bash
remark README.md
```

both of the above broke.

Piping seems to work
``` bash
remark < README.md
```

**Comment by wooorm** [comment]
OK, working on `try ... catch`.

Would you be able to test the [`bug/fix-windows-piping`](https://github.com/wooorm/remark/tree/bug/fix-windows-piping) branch? Clone the repo, then:

```
cd remark
npm install
npm link
cd $YOUR_PREVIOUS_PLACE
remark README.md
```

And post the results?

**Comment by ChristianMurphy** [comment]
The command
``` bash
remark *.md
```

Returns
``` bash
CONTRIBUTING.md: no issues found
DESIGN.md: no issues found
README.md: no issues found
```

The commands
``` bash
remark README.md
remark < README.md
```
Both work as well. :smile: :+1:

**Comment by wooorm** [comment]
That’s a fix, right? Or should there’ve been errors in `remark *.md`?

**Comment by ChristianMurphy** [comment]
That's a fix :+1:

**Comment by ChristianMurphy** [comment]
Thanks @wooorm !

**Comment by wooorm** [comment]
No problem, thanks for pinging me!

I’ll have a new release out in a sec.
