### ISSUE TITLE
Document path globs support

### ISSUE THREAD

**Issue by radek-holy** [wooorm/remark#120]
Hello,
I'd like to ask you to implement support for specifying input files by globs. That would allow us to run `remark` from build (e.g. npm) scripts in a portable (cross-platform) way. There is actually a lot of linters that accept globs already. They use [minimatch](https://www.npmjs.com/package/minimatch) AFAIK. I mean some module based on it like [globby](https://www.npmjs.com/package/globby), [glob-all](https://www.npmjs.com/package/glob-all), [globule](https://www.npmjs.com/package/globule) or [simple-glob](https://www.npmjs.com/package/simple-glob).

**Comment by wooorm** [comment]
Remark has support for globs, and uses minimatch, globby, internally. Could you show me a test case which doesn’t work?

**Comment by radek-holy** [comment]
Sure, let me change this issue to a request to document the support. I'll create another report for the issue.

**Comment by wooorm** [comment]
Thanks for the issue. I’m not sure what kind of documentation you expect though. There are already some examples of `.` usage in <https://github.com/wooorm/remark#cli> and <https://github.com/wooorm/remark/blob/master/doc/remark.1.md>. What do you suggest?

**Comment by radek-holy** [comment]
AFAIK, `.` is not a glob. Or at least it's not a wildcard. Or in other words, the path `.` can be handled without any support of globs and thus it's hard to deduce whether globs are supported or not.

Anyway, ideally, you could mention the supported glob syntax (at least something like this: https://www.npmjs.com/package/globby#globbing-patterns). But if it's too much, adding an example with `*` could be enough.

**Comment by radek-holy** [comment]
Cool, thanks

**Comment by davidtheclark** [comment]
@wooorm Does this module still use globby internally? I can't find usage of it in this repo or in unified-args. And I'm struggling to figure out how to pass globs with negation (`!`) — which I think will be a more performant way to ignore all Markdown within `node_modules` than an ignore file, allowing me to use a broad `**/*.md` glob (e.g. `**/*.md, !**/node_modules/**`)

**Comment by wooorm** [comment]
@davidtheclark 👋

Did you find [`unified-engine`](https://github.com/unifiedjs/unified-engine)? It’s what powers `unified-args`. The stuff you’re looking for is probably here:

https://github.com/unifiedjs/unified-engine/blob/b5bb6e2986efc0644d78c22ccf78855e630f5312/lib/finder.js#L37-L68

I only know of negation patterns due to the [ignore part](https://github.com/unifiedjs/unified-engine/blob/master/lib/ignore.js) (for remark, `.remarkignore`). It used to be ported over from ESLint, but now it’s externalised and in [`node-ignore`](https://github.com/kaelzhang/node-ignore).

Note: what exactly are you doing? Globbing may be faster, but the file-in-directory finding itself shouldn’t be super slow either!

**Comment by davidtheclark** [comment]
> what exactly are you doing?

I have repos with more Markdown files to lint that just at the root level. Often there's a `docs/` directory full of files. Sometimes there are subdirectories with `README.md`s of their own. Sometimes there's a monorepo with `packages/` that each have their own possibilities. I'd love to recursively search for all `.md` files *without* entering any `node_modules` subdirectories.

**Comment by wooorm** [comment]
👍

Why not just use 'remark .'? That should cover all cases!

**Comment by davidtheclark** [comment]
Oh geez, I'm sorry! I think while iterating on something I confused myself into thinking that `remark .` was only ever touching the root directory. Turns out it works. Thanks for the help!

**Comment by wooorm** [comment]
Oh no problem at all! Yeah the directory search stuff is pretty powerful. Let me know if you have suggestions for doc additions to make this more clear!

**Comment by karlhorky** [comment]
One thing that would be cool to have in the docs is a globby example for MDX files.

I am using `remark-cli` with [`remark-lint-no-dead-urls`](https://github.com/davidtheclark/remark-lint-no-dead-urls/) and I'm using the following in my `package.json`:

```json
{
  "scripts": {
    "lint-md": "remark \"src/pages/**/*.mdx\""
  }
}
```
