### ISSUE TITLE
Read file list from a file

### ISSUE THREAD

**Issue by radek-holy** [wooorm/remark#122]
I just realized that there is no cross-platform way to use environment variables in NPM scripts. So, I guess that the only way to have a single source of file patterns is to store them in a file. Can you please consider adding a support to read the patterns from files? I would prefer a simple text file over e.g. a JSON file.

**Comment by wooorm** [comment]
Which environment variable are you referring to? The only ones used by remark are [`$DEBUG`](https://github.com/wooorm/remark/blob/master/doc/remark.1.md#description) for debugging and [`$TEST_EXTENDED`](https://github.com/wooorm/remark/blob/fa1f0c1098e9f20f2c877e62a43c807813454076/package.json#L106) which can optionally used when running tests internally.

And, on a related note, which patterns? Do you mean globs?

**Comment by radek-holy** [comment]
I apologize for not being clear. I originally wanted to store the list of markdown globs passed to all markdown lints in an environment variable and pass it to them like this: `remark $MD_GLOBS`. Unfortunately, this does not work on all the major operating systems (i.e. Windows). So, I'd like to do something like `remark --input-file md.manifest`.

Yes, I mean globs.

**Comment by wooorm** [comment]
I feel like that’s out of the scope of remark.

On my set-up, something like this works:

```sh
$ ls *.md > list.txt
$ cat list.txt
# history.md
# readme.md

# now edit `list.txt` to your liking, and then:

$ remark $(< list.txt)
# history.md: written
# readme.md: written
```

Additionally, there’s already support for extensive file-finding.Specify `.`, and use [`.remarkignore`](https://github.com/wooorm/remark/blob/master/doc/remarkignore.5.md) (and optionally the [`-e, --ext`](https://github.com/wooorm/remark/blob/master/doc/remark.1.md#-e---ext-extensions) flag).

**Comment by radek-holy** [comment]
Wow, this `$(< ...)` is new to me. Unfortunately, it does not work on Windows (just guessing but I am pretty sure). And the combination of `.` and `.remarkignore` is not compatible with other tools.

Anyway, feel free to close this. This is just nice to have...

**Comment by wooorm** [comment]
Probably unix only, indeed. That above example works because (some?) shells automatically change newlines to spaces in certain cases.

Anyway, I’ll keep this in mind but I don’t think this is going to be implemented. Thanks for raising the issue though!
