### ISSUE TITLE
Potential bug parsing arbitrary HTML inside markdown

### ISSUE THREAD

**Issue by yaycmyk** [wooorm/remark#124]
I noticed that for an arbitrary `<a>` tag, it was actually getting split into two separate `HTML` mdast nodes.

For an input of:

```md
# Enigma Platform Team<a id='enigma-platform-team' href='#enigma-platform-team'></a>
```

I'm seeing an emitted structure of (position disabled):

```json
{
    "type": "root",
    "children": [
        {
            "type": "heading",
            "depth": 1,
            "children": [
                {
                    "type": "text",
                    "value": "Enigma Platform Team"
                },
                {
                    "type": "html",
                    "value": "<a id='enigma-platform-team' href='#enigma-platform-team'>"
                },
                {
                    "type": "html",
                    "value": "</a>"
                }
            ]
        }
    ]
}
```

Should be a single HTML node, no?

**Comment by wooorm** [comment]
I’m don’t think so. Other parsers don’t do this either: [Commonmark (click the AST tab)](http://spec.commonmark.org/dingus/?text=%23%20Enigma%20Platform%20Team%3Ca%20id%3D'enigma-platform-team'%20href%3D'%23enigma-platform-team'%3E%3C%2Fa%3E%0A) and [markdown-it](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%23%20Enigma%20Platform%20Team%3Ca%20id%3D%27enigma-platform-team%27%20href%3D%27%23enigma-platform-team%27%3E%3C%2Fa%3E%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22debug%22%7D%7D).

And the CommonMark spec has this to say:

> An HTML tag consists of an open tag, a closing tag, an HTML comment, a processing instruction, a declaration, **or** a CDATA section.

(emphasis mine)

Most important: don’t expect “HTML” found in markdown to be valid. Adding a stray `</div>` somewhere is perfectly valid in markdown. And, it can be dangerous, that’s why [remark-vdom](https://www.npmjs.com/package/remark-vdom) and [mdast-react](https://www.npmjs.com/package/mdast-react) don’t allow it.

If you really want this I suggest creating a [transformer](https://github.com/wooorm/remark/blob/master/doc/remarkplugin.3.md#function-transformernode-file-next).

**Comment by yaycmyk** [comment]
I'm curious why that is... it looks like CommonMark will interpret text inside of arbitrary HTML as actual textNodes, which tells me they're actually attempting to parse the HTML, or are using fast and loose regexes.

As far as Markdown compilers are concerned, arbitrary HTML is kind of a black box, isn't it? I think it makes sense to coalesce the block into a single node so it can simply be plopped in place. More error prone if you don't, IMO.

**Comment by wooorm** [comment]
The reason why they’re separate is that `<kbd>*foo*</kbd>` gets rendered as follows: <kbd>*foo*</kbd>, an emphasised keyboard shortcut. That’s very logical and useful in my opinion, and that’s why all those others and remark do this. :wink:

**Comment by yaycmyk** [comment]
`kbd` is styled by the user agent sheet though and with CSS...

**Comment by wooorm** [comment]
But the emphasis isn’t? Sorry but I don’t get it: the fact that you can use markdown inside inline-HTML is *magical*. :rainbow: Why wouldn’t anyone want this?

**Comment by yaycmyk** [comment]
Yeah I get it now with that `kbd` example - thanks.

**Comment by yaycmyk** [comment]
Revisiting this, would it be possible to have an ID to relate the first HTML fragment to its closer? I would just look for the next available HTML node, but it seems like it might be possible to have two sets of nested HTML nodes, which would screw up a simple forward search.

**Comment by wooorm** [comment]
For clarity, what output do you expect, for example for: `<span><strong></em></code>`? Which yields:

```json
{
  "type": "root",
  "children": [
    {
      "type": "paragraph",
      "children": [
        {
          "type": "html",
          "value": "<span>"
        },
        {
          "type": "html",
          "value": "<strong>"
        },
        {
          "type": "html",
          "value": "</em>"
        },
        {
          "type": "html",
          "value": "</code>"
        }
      ]
    }
  ]
}
```

**Comment by yaycmyk** [comment]
Nevermind, I just thought of an algorithm to deal with it. Thanks!
