### ISSUE TITLE
cli: AST input

### ISSUE THREAD

**Issue by eush77** [wooorm/remark#126]
Currently `remark(1)` can process in `markdown⟶markdown` mode or `markdown⟶AST` (with `-a --ast`).

It would be useful to support some kind of AST input so that `AST⟶markdown` and `AST⟶AST` operation modes would be possible, too.

This would be useful for quickly processing documents with JSON processors (like [jq]) when a plugin does not exist / is not general enough or for testing plugins on predefined or manually constructed mdast trees.

[jq]: https://stedolan.github.io/jq/

**Comment by wooorm** [comment]
Definitely! This would additionally be a great way to patch remark/retext/hast together!  For example, `remark -a -u lint | to-nlcst | retext -a -u spell -s | to-mdast | remark -s`.

However, both `-s` and `-S` are already in use. And so is `-c` (for compile). What would be a great name?

**Comment by eush77** [comment]
`-m --mdast` or `-r --raw` are both unused.

But then there is an issue with `-a --ast` (I think): when `remark(1)` gets the feature of reading AST input, `--ast` becomes ambiguous. So the options for AST input/output should probably come in pair: something like `--ai --ast-input` / `--ao --ast-output`. `-a --ast` could enable both.

**Comment by wooorm** [comment]
Oh right. So `-a` should stand for both `--ast-in` and `--ast-out`, agreed.
We could opt for no short flags for these two.

Maybe though `-t` would be better (as the same could be used for retext, which has a CST): `-t`, `--tree-in`, and `--tree-out`?
That would result in `remark readme.md -u lint --tree-out | to-nlcst | retext -u spell -t | to-mdast | remark --tree-in`.

**Comment by eush77** [comment]
Both `--ast` and `--tree` are fine to me. I can also suggest `--json`.
