### ISSUE TITLE
Something I don't understand from plugins.md

### ISSUE THREAD

**Issue by chcokr** [wooorm/remark#130]
I'm trying to deprecate the `mdast-lint-sentence-newline` after the rename. I read the following in `plugins.md` and I don't quite get it:

> Then, create a near-empty project with a readme.md (pointing to to remark-html on GitHub or npm), and a deprecation notice, and publish it as mdast-foo@2.0.0 (yes, a major bump too).

Why should we point to `remark-html` in particular in the README?

**Comment by wooorm** [comment]
Whoops, that should’ve been `remark-foo`, thus, the project you’re currently renaming :)
