### ISSUE TITLE
Remark throws error if "lint" is in .remarkrc

### ISSUE THREAD

**Issue by eppsilon** [wooorm/remark#131]
Hi,

I've found that remark throws an error when I attempt to lint a file with the lint plugin configured in .remarkrc. I have remark 3.1.3 and remark-lint 2.0.3 installed globally.

```
remark -u remark-lint [file]
1:1  error    Error: Cannot find module 'lint'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at findPlugin (/usr/local/lib/node_modules/remark/lib/cli/file-pipeline/configure.js:140:12)
    at /usr/local/lib/node_modules/remark/lib/cli/file-pipeline/configure.js:199:26
    at handleLocalConfiguration (/usr/local/lib/node_modules/remark/lib/cli/configuration.js:294:9)
    at /usr/local/lib/node_modules/remark/lib/cli/configuration.js:211:9
    at /usr/local/lib/node_modules/remark/node_modules/vfile-find-up/index.js:207:17
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Here is .remarkrc:

```
{
  "plugins": {
    "lint": {
      ... (lots of rules) ...
    }
  }
}
```

Changing `lint` to `remark-lint` fixes the problem, but that doesn't match the example in `remark-lint`'s [readme](https://github.com/wooorm/remark-lint#configuring-remark-lint).

**Comment by wooorm** [comment]
I just tested this with:

This `.remarkrc`:

```md
{
  "plugins": {
    "lint": {
      "no-html": false
    }
  }
}
```

This `example.md`:

```md
Alpha bravo charlie delta echo foxtrot golf hotel india Juliet kilo lima mike November this line is too long.

<span></span>
```

I have installed remark and remark-lint globally:

```sh
🚀  ~/projects/oss/example: remark -V
3.1.3
```

These are all the files:

```sh
🚀  ~/projects/oss/example: ls -la
total 16
drwxr-xr-x   4 tilde  staff  136 10 Jan 10:29 .
drwxr-xr-x  19 tilde  staff  646 10 Jan 10:28 ..
-rw-r--r--   1 tilde  staff   66 10 Jan 10:32 .remarkrc
-rw-r--r--   1 tilde  staff  125 10 Jan 10:30 example.md
```

...and things work as expected:

```sh
🚀  ~/projects/oss/example: remark example.md 
Alpha bravo charlie delta echo foxtrot golf hotel india Juliet kilo lima mike November this line is too long.

<span></span>
example.md
      1:110  warning  Line must be at most 80 characters  maximum-line-length

⚠ 1 warning
```

To resolve this, could you:

*   Run `DEBUG="*" remark your-file.md`, and post the result;
*   Let me know which `node -v` and `npm -v` results you get;
*   Post the result of `ls -la node_modules`.

That would make things easier for me to debug your case :)

**Comment by wooorm** [comment]
Closing due to no response.

**Comment by rarkins** [comment]
I hit the same issue - doesn't seem to be isolated.

**Comment by wooorm** [comment]
Just now noticed that this problem here is the same as wooorm/remark-lint#70 (`lint` and `remark-lint` in multiple places).

@rarkins, is your issue still the same as wooorm/remark-lint#70, or is this another problem?

**Comment by rarkins** [comment]
@wooorm This here was the "original" problem I had - `lint` didn't work but `remark-lint` did. Things started working once I renamed it and I didn't try it again after that.
