### ISSUE TITLE
Parse error about HTML block

### ISSUE THREAD

**Issue by azu** [wooorm/remark#137]
I try to parse following text and remark throw error.

remark: 3.2.0

```js
var remark =require("remark")
var processor = remark();
var doc = processor.process(`<pre><code class="lang-diff">

 module.exports = {
   handleLogout: handleLogout,
-  handleNotFound: handleNotFound
+  handleNotFound: handleNotFound,
+  handleBadRequest: handleBadRequest
 };</code></pre>`);
```

> TypeError: Cannot read property 'charAt' of undefined

DEMO: https://tonicdev.com/569e3cc6aff8f40c00dbabb1/569e3cc6aff8f40c00dbabb2

Original issue come from https://github.com/textlint/textlint/issues/104

Thanks.

**Comment by wooorm** [comment]
I have an upcoming fix, but do note that the blank line means `+` and `-` are rendered as lists!

**Comment by azu** [comment]
@wooorm Thanks!
