### ISSUE TITLE
No option for tight list items?

### ISSUE THREAD

**Issue by catesandrew** [wooorm/remark#138]
I'm just curious, why isn't there an option for tight list items? I prefer to write my lists like this:

```markdown
-   First item
-   Second item
```

But remark always 'loosifies' them to 

```markdown
-   First item

-   Second item
```

why?

**Comment by wooorm** [comment]
If I’m right, it doesn’t loosen them if they’re not loose in the input?

```txt
🚀  remark master [?]: cat ex.md 
-   First item
-   Second item
🚀  remark master [?]: bin/remark --no-rc --silent ex.md 
-   First item
-   Second item
```

**Comment by catesandrew** [comment]
ok, so it takes what's given as a precedence. i'll investigate further. has to be something up the line being used programmatically or with rc fils. thanks for answering question, i'll close it now.
