### ISSUE TITLE
Entities in references and definitions

### ISSUE THREAD

**Issue by wooorm** [wooorm/remark#141]
Entities in references and definitions are currently compiled in a way which removes their bond:

```md
[foo&amp;bar][]

[foo&amp;bar]: http://example.com
```

Is compiled to:

```md
[foo&bar][]

[foo&amp;bar]: http://example.com
```

@eush77, I think this has to do with [`unescapeShortcutLinkReference`](https://github.com/wooorm/remark/blob/8ff7ab436cdcd0daf0f1210fb65ad46976449bdc/lib/stringify.js#L1828), which you you added in d1fe019. Could you take a look at this?

**Comment by eush77** [comment]
Seems like it's easy to fix, I'll look closely...

**Comment by wooorm** [comment]
:+1:
