### ISSUE TITLE
Using webpack Module not found: Error: Cannot resolve module 'json-loader'

### ISSUE THREAD

**Issue by AlastairTaft** [wooorm/remark#155]
This might be more of a webpack specific question but I'm struggling to include this module to use client side.

I always get the following error.

```
ERROR in ./~/remark/index.js
Module not found: Error: Cannot resolve module 'json-loader' in /path/to/my/project/node_modules/remark
 @ ./~/remark/index.js 21:13-41
```

My webpack config has a json loader but it can't seem to resolve.

```
module: {
    loaders: [
      {
        test: /\.json$/,
        loader: 'json-loader',
      }, 
      ...
    ]
   ...
} 
```

Would appreciate some help if anyone else has ran into the same issue.

**Comment by wooorm** [comment]
Hey @AlastairTaft, thanks for using (or, trying to use) remark!

I don’t use webpack, I’m not familiar with how it works. From the error you mentioned this, I think that this is a webpack problem and not a remark problem. (as remark, on the given line, does point to an existing JSON file with a correct extension: <https://github.com/wooorm/remark/blob/master/index.js#L2>)

Unfortunately, I cannot help with webpack problems, I’ll leave this open as maybe someone will stumble upon an answer in the coming few days, or will close this in the foreseeable future.

**Comment by AlastairTaft** [comment]
Thanks wooorm for the fast reply. 

Found out that the issue was something really dumb. After trying for a long time to get the loaders to resolve to the `node_modules` directory I finally figured out I was actually missing the loader. `npm install json-loader --save-dev` solved the problem.

Looking forward to trying your module out now.

**Comment by wooorm** [comment]
Oh wow, that’s quite typical haha, always check your deps! :wink:

Good luck!
