### ISSUE TITLE
code block after list bugs out

### ISSUE THREAD

**Issue by yoshuawuyts** [wooorm/remark#169]
This bugged out with me. Remove the `\` for the actual code. It causes the code block to not end when it should.
```markdown
1. foo
2. bar
\`\`\`sh
$ foo bar
\`\`\`
- [some](link)
```

Thanks!

**Comment by wooorm** [comment]
Yeah, GH doesn’t like nested code :/

Thanks, agreed!

**Comment by wooorm** [comment]
Thanks for reporting, I fixed it but I’ll delay the release a bit. Probably later this week!

**Comment by yoshuawuyts** [comment]
heaps rad, thanks! :D
