### ISSUE TITLE
Configuration file as JavaScript file

### ISSUE THREAD

**Issue by paazmaya** [wooorm/remark#170]
How about allowing to use JavaScript as the configuration file, which would `module.exports = {};` the configuration?
In the same manner as ESLint (http://eslint.org/docs/user-guide/configuring#configuration-file-formats) or StyleLint (http://stylelint.io/user-guide/configuration/) does it...

Related to https://github.com/wooorm/remark/blob/master/doc/remarkrc.5.md

**Comment by wooorm** [comment]
Thanks for the issue. Nice idea, I’m willing to accept a PR for this!

**Comment by paazmaya** [comment]
@wooorm any reason why simply `require()` is not used for the configuration file?
Instead there seems to be this `parseJSON` method, https://github.com/wooorm/remark/blob/master/lib/cli/cli.js#L63

**Comment by wooorm** [comment]
That is for CLI settings, e.g., `remark -s foo:true,bar:'baz'` Integrating with [`.remarkrc` happens here](https://github.com/wooorm/remark/blob/master/lib/cli/configuration.js)!

**Comment by paazmaya** [comment]
Thank you!
Then changing the https://github.com/wooorm/remark/blob/master/lib/cli/configuration.js#L134 to `require()` would seem to do it.
I shall PR with :grapes:

**Comment by wooorm** [comment]
Whoops, forgot to close in cd59707.
