### ISSUE TITLE
Add support for promises

### ISSUE THREAD

**Issue by zkochan** [wooorm/remark#174]
remark has a lot of functions that can be asynchronous. I suggest to support promises not only callbacks and make the function asynchronous only, because as the NodeJS documenation says:

> It is very important for APIs to be either 100% synchronous or 100% asynchronous.

for supporting different kinds of async functions this package can be used - [run-async](https://npmjs.org/package/run-async). Specifically the `runAsync.cb` method. (runAsync is used by huge projects like inquirer and yeoman)

I can create a pull request if you like the idea

**Comment by wooorm** [comment]
Transformers can already be async. It’s undocumented, but [they can return a `Promise`](https://github.com/segmentio/ware/#usefn), if you’re so inclined.

I don’t personally want promises in libraries. They’re nice if authors want to use them, but libraries shouldn’t force promises upon authors.

Whether the API executes sync or async, is defined by which plug-in’s an author uses. As that’s the users choice, it makes no sense to create different API for that: remark just “copes” with whatever you throw at it, be it sync or async.

**Comment by zkochan** [comment]
ok, great!

In that case it would be nice to document that it is possible to use a transformer that returns a promise. That was the only reason I've created the issue.
