### ISSUE TITLE
Add the possibility to test markdown files

### ISSUE THREAD

**Issue by zkochan** [wooorm/remark#175]
In order to guarantee that the markdown files are up to date, add the possibility to test them with remark.

*Real life example.* Lets suppose **remark-toc** is used to generate a table of contents. If someone updates some of the headings, the TOC will become out of date.

A command like `remark test` would regenerate the markdown file and compare it to the one that is in the filesystem. If the files don't match, it means that the markdown file is out of date or incorrect.

`remark test` could be used in the test script of package.json for verifying that markdown files are correct.

I've created a tool for doing this kind of stuff ([mos](https://github.com/zkochan/mos)) but then I've found remark and realized that I can rewrite my tool to be a remark plugin, if remark will have this testing feature. The testing feature would be especially good for this plugin that can generate examples ([mos-plugin-example](https://github.com/zkochan/mos/tree/master/plugins/mos-plugin-example))

**Comment by wooorm** [comment]
1. if you’re going to run a shell command, why not just run `remark` with [`-o`](https://github.com/wooorm/remark/blob/master/doc/remark.1.md#-o---output-path) to actually update the TOC?

2. Diffing should be possible, though I think it should stay out of the core, instead in a plug-in.

**Comment by zkochan** [comment]
1. Because there are use cases for testing the markdown. Updating wouldn't work because you might not need an update, maybe you did an error and you have to manually update the code. Check, for instance, this tool for testing markdown examples [markdown-doctest](https://github.com/Widdershin/markdown-doctest)

2. OK, maybe you are right, time will show. I will create such a plug-in.

**Comment by wooorm** [comment]
1. Well, I use remark to always generate Usage examples (`remark-usage`) and TOCs (`remark-toc`) for me, check coding style (`remark-lint`), whether links point to real things (`remark-validate-links`). These plug-ins are designed to auto-update READMEs to stay up to date, or fail if something is not ok. I execute `remark . -o` (in `npm test`) locally and on the CI (before a release), to ensure no out-of-date docs are committed / published. Even if I forget something, the release will include fixed docs, or halt the release if that’s impossible.

    In fact, `remark-usage` looks quite like the project you mentioned, it also halts the CI for broken examples.

2. :+1:

**Comment by wooorm** [comment]
Thought about this some more; closing this as I think it’s no longer related to code in this repo. If you need my help, use the Gitter channel, and if you have another suggestion, open another issue!

**Comment by zkochan** [comment]
ok, thanks

**Comment by zkochan** [comment]
Just a follow up. Instead of creating a remark module for testing, I have extended my module, that already tests markdown files, with the possibility to [use custom remark plugins](https://github.com/zkochan/mos#remark-plugins).

**Comment by wooorm** [comment]
Awesome, very cool!
