### ISSUE TITLE
Bad line number for empty section marker

### ISSUE THREAD

**Issue by tkruse** [wooorm/remark#177]
Hi, using nodejs 4.0.0, and remark config as below, I get this error report below. What is confusing is that it does not really tell users to fix the `#####` part, nor in which line this part is. It would be nice if remark could provide better output for this case, including a hint that there is something bad around the `#####`.

```
# Title

Text

#####

more text
```

```
./node_modules/.bin/remark example.md --no-color -q --config-path ./remark/.remarkrc 1
example.md
        1:1  warning  Add 7 spaces before this heading’s content  no-heading-content-indent
```

```
{
  "name": "example",
  "version": "0.0.0",
  "description": "example",
  "private": true,
  "dependencies": {
    "remark": "^4.2.0",
    "remark-lint": "^3.2.0",
    "remark-lint-sentence-newline": "^2.0.0",
    "remark-validate-links": "^3.0.0"
  }
}
```

```
{
"plugins": {
    "remark-lint": {
        "unordered-list-marker-style": "consistent",
        "list-item-bullet-indent": false,
        "list-item-indent": false,
        "list-item-spacing": false,
        "no-html": false,
        "maximum-line-length": false,
        "no-file-name-mixed-case": false,
        "heading-increment": false,
        "no-multiple-toplevel-headings": false,
        "no-consecutive-blank-lines": false,
        "maximum-line-length": 9000,
        "maximum-heading-length": 300,
        "no-heading-punctuation": false,
        "no-duplicate-headings": false,
        "emphasis-marker": "*",
        "no-tabs": false,
        "blockquote-indentation": false,
        "strong-marker": "*"
    }
  },
  "settings": {
    "bullet": "*",
    "listItemIndent": "1",
    "strong": "*",
    "emphasis": "*"
  }

}
```

**Comment by wooorm** [comment]
Hey @tkruse, thanks for reporting! The error you get is wrong; I’ll look into removing it, as a fix.

What warning would you suggest? Considering that an empty header is perfectly valid (although pretty useless probably).

P.S. Oh and could you post lint-related questions to `wooorm/remark-lint` in the future? Makes it a little bit easier for me :)

**Comment by tkruse** [comment]
I guess an empty header should be a warning, it is not just uselss, but can only cause bad things for rendering and transforming. I can try rememering remark-lint for next time, but no promise.

**Comment by wooorm** [comment]
Closed by https://github.com/wooorm/remark-lint/commit/1f2e9a8a91826da74cd8870860e379048524c1d2. If you want a rule, e.g., `no-empty-heading`, suggest it over at remark-lint, and I’ll look into that for the next release!
