### ISSUE TITLE
Provide support for source maps

### ISSUE THREAD

**Issue by tadatuta** [wooorm/remark#178]

**Comment by wooorm** [comment]
Nice idea! I’m not too familiar with the inner workings of source maps to help you in producing this though. However, I believe the [exposed nodes do hold enough information](https://github.com/wooorm/unist#location) to produce maps.

Also, this is better left to user-land [as a plug-in](https://github.com/wooorm/remark/blob/master/doc/plugins.md#creating-plugins) instead of the core.

**Comment by tadatuta** [comment]
I really think it should be supported in core. Plugins just need to follow some convention to make it work.
E.g. CSS preprocessors, `postcss`, gulp, webpack, etc. have support in core.
Otherwise even with support of source maps in some plugin it'll impossible to create a chain with other plugins lacking such support.

**Comment by wooorm** [comment]
The fact that PostCSS, Gulp, and Webpack have this is their core does not mean remark should, too.
For example, Gulp and Webpack solve very different things. And for PostCSS: having source maps for CSS is quite useful because web inspectors integrate with CSS, which cannot be said for markdown.

> I really think it should be supported in core.

Now, I don’t know much about source maps, as previously mentioned, but I do know quite a lot about remark and there isn’t much which couldn’t be solved outside the core. I doubt source maps are one of them. 

I’d like to see reasoning for this. Why?

> Otherwise even with support of source maps in some plugin it'll impossible to create a chain with other plugins lacking such support.

Why?

**Comment by tadatuta** [comment]
My use case is to compile markdown to JS tree structure via chain of plugins and afterwards being able to find out which line of markdown produced with line of the result tree.

Also I want is to add any existent `remark`'s plugins to a chain and still have maps to source markdown. And as so each plugin should provide needed data or it should be provided via core as an option.

**Comment by wooorm** [comment]
You're describing remark: that's exactly what it already is!

**Comment by tadatuta** [comment]
True. That's why I'm making this feature request in this repo ;)
The only missing thing is support for automatic source map generation after each step of plugins chain.

**Comment by wooorm** [comment]
Ah, I get it. I’ll think about this some more!

**Comment by wooorm** [comment]
You keep mentioning you need remark with source maps, but why? Your posing an [XY problem](http://xyproblem.info).

---

So, first of all, if plug-ins add markdown content (nodes). Those nodes, called [“generated”](https://github.com/wooorm/unist#location) nodes, do not have positional information. Positional information is for things which originate in the input file.

The only way to know where content ends up, is in the compiler (theoretically), when nodes are actually stringified. Thus, it’s not possible to to create a source map without stringifying the syntax tree. And I don’t think that should be done after each step in the plug-in chain.

Now, knowing where content ends up isn’t very easy, as compilation occurs bottom-to-top: first text is compiled (e.g., escaped), then it’s wrapped in emphasis, then concatenated in a paragraph, then wrapped in a blockquote (each line prefixed with `> `), then concatenated with other blocks (and footnotes?).

**Comment by tadatuta** [comment]
> Your posing an XY problem.

I described what I need at https://github.com/wooorm/remark/issues/178#issuecomment-215213408

> Now, knowing where content ends up isn’t very easy...

I didn't catch the idea. If I have `source.md`, need to apply a few plugins to it and get something like
```js
{
    block: 'para',
    content: [
        'part 1 ',
        {
            block: 'link',
            url: 'http://site.com/',
            content: 'click me'
        },
        ' part2'
    ]
}
```

what is the way to find out which position of `source.md` produced `url` field of `link` block?

**Comment by wooorm** [comment]
> I described what I **need** at #178 (comment)

(emphasis mine)

You’re describing what (you think) you need. I think I know another way. But I need to know why you want the source maps.

From that link, I feel that’s exactly what’s going on here:

> 1. User wants to do X.
2. User doesn't know how to do X, but thinks they can fumble their way to a solution if they can just manage to do Y.
3. User doesn't know how to do Y either.
4. User asks for help with Y.
5. **Others try to help user with Y, but are confused because Y seems like a strange problem to want to solve.**
6. **After much interaction and wasted time, it finally becomes clear that the user really wants help with X, and that Y wasn't even a suitable solution for X.**

**Comment by wooorm** [comment]
Oh, and on the second part of your comment: the code in your comment is close to a reason mentioned above. But I’m not sure if that is a sample of what you want, or exactly what you want. Is it?

**Comment by tadatuta** [comment]
yes, that's exactly what I want but I want it to work in the way source maps work, e.g. open an HTML page with `<script src="path/to/generated-from-source.md.js">` and being able to see source lines in web inspector, etc.

still if there's easier way to solve it, I'll be happy to follow your recomendations.

**Comment by wooorm** [comment]
> <script src="path/to/generated-from-source.md.js">

Where’s `.js` coming from? How does one open markdown in a browser?

---

I investigated source maps, and I’m not adding them, for these reasons:

1) Source maps support, turned on by default, would significantly decrease performance;
2) Source maps make sense in the browser, for CSS and JS (I don’t know of any HTML processor with source maps support), not for markdown; In fact, I don’t think any browser supports non-JS and non-CSS source maps?
3) Adding source maps isn’t easy.

I’ll reconsider if someone provides a working PR which addresses these issues.

---

Back to what remark does: it processes markdown, and exposes a syntax tree to plug-ins, which can modify those nodes to transform the document. Those nodes have positional information.

* Read more about plug-ins in the docs for [remarkplugin(3)](https://github.com/wooorm/remark/blob/master/doc/remarkplugin.3.md).
* Regarding locations, I suggest trying the demo out: <http://remark.js.org/demo/> (click “show setting”, and select “Output?”: “JSON”). But also: read the docs for [mdast](https://github.com/wooorm/mdast).

E.g., the following markdown:

```md
Alpha [bravo](https://charlie.com) delta.
```

Yields:

```json
{
  "type": "root",
  "children": [
    {
      "type": "paragraph",
      "children": [
        {
          "type": "text",
          "value": "Alpha ",
          "position": {
            "start": {
              "line": 1,
              "column": 1
            },
            "end": {
              "line": 1,
              "column": 7
            },
            "indent": []
          }
        },
        {
          "type": "link",
          "title": null,
          "href": "https://charlie.com",
          "children": [
            {
              "type": "text",
              "value": "bravo",
              "position": {
                "start": {
                  "line": 1,
                  "column": 8
                },
                "end": {
                  "line": 1,
                  "column": 13
                },
                "indent": []
              }
            }
          ],
          "position": {
            "start": {
              "line": 1,
              "column": 7
            },
            "end": {
              "line": 1,
              "column": 35
            },
            "indent": []
          }
        },
        {
          "type": "text",
          "value": " delta.",
          "position": {
            "start": {
              "line": 1,
              "column": 35
            },
            "end": {
              "line": 1,
              "column": 42
            },
            "indent": []
          }
        }
      ],
      "position": {
        "start": {
          "line": 1,
          "column": 1
        },
        "end": {
          "line": 1,
          "column": 42
        },
        "indent": []
      }
    }
  ],
  "position": {
    "start": {
      "line": 1,
      "column": 1
    },
    "end": {
      "line": 1,
      "column": 42
    }
  }
}
```

**Comment by tadatuta** [comment]
> Where’s .js coming from?

That's a result of markdown transformation via chain of `remark` plugins.

> How does one open markdown in a browser?

The idea was to one JS and even HTML generated with that JS and still be able to follow to source in markdown.

> 1) Source maps support, turned on by default, would significantly decrease performance;

Sure it should be optional.

> 2) Source maps make sense in the browser, for CSS and JS (I don’t know of any HTML processor with source maps support), not for markdown; In fact, I don’t think any browser supports non-JS and non-CSS source maps?

My goal is to parse markdown and generate files which are understandable for browsers of course. And still to have possibility to find source of each node.

As for source maps for HTML, there's plenty of them. Try to search for something like `template engine source maps`.

Also take a look at https://github.com/chjj/marked/issues/382

> 3) Adding source maps isn’t easy.

Otherwise I'd implement it myself ;)

> Those nodes have positional information

That's true, but such information is useless after plugins which transform initial tree to something new, isn't it?

**Comment by wooorm** [comment]
> > Where’s .js coming from?
> 
> That's a result of markdown transformation via chain of `remark` plugins.

remark doesn’t compile to JavaScript. You’ll need a resource to be loaded **and executed** by the browser (that’s why CSS and JS are so common) to benefit from source maps.

> > How does one open markdown in a browser?
> 
> The idea was to one JS and even HTML generated with that JS and still be able to follow to source in markdown.

I can imagine HTML, but that’s for remark-html, not the core of remark (which deals only with markdown).

> As for source maps for HTML, there's plenty of them. Try to search for something like `template engine source maps`.

I checked the first ten results. They are template engines which work in the browser (being a JavaScript library), and those libraries have source maps. I also checked Haml and Pug/Jade, they don’t have source maps either.

> Also take a look at https://github.com/chjj/marked/issues/382

The marked issue is a feature request, like this one, it isn’t integrated.

> > 3) Adding source maps isn’t easy.
> 
> Otherwise I'd implement it myself ;)

I suggest PRing to remark-html. But first make sure browsers support source maps for HTML documents.

> > Those nodes have positional information
> 
> That's true, but such information is useless after plugins which transform initial tree to something new, isn't it?

Source maps map “origin” locations to “destination” locations. The nodes in remark have their “origin” locations. As mentioned previously, the destination locations can be gathered upon compilation. Thus half of the data is already available.

**Comment by tadatuta** [comment]
> remark doesn’t compile to JavaScript

`remark` generates AST in JS which after some simple transformation is what I need as a result. why can't I say that `remark` can be used for such JS generation?

> I can imagine HTML, but that’s for remark-html, not the core of remark

My goal is to generate special JS format and them generate HTML upon it with some other tools. So `remark-html` won't fit.

> I also checked Haml and Pug/Jade, they don’t have source maps either

https://github.com/sidorares/pugify

> The marked issue is a feature request, like this one, it isn’t integrated.

Yes, I decided to post that link to show that I'm not the only one ;)


Anyways I understand it's a quite unpopular feature and it's possible to live without it :)

**Comment by wooorm** [comment]
> remark generates AST in JS which after some simple transformation is what I need as a result. why can't I say that remark can be used for such JS generation?

It creates JSON. If you’re going to create JS, you’re doing something which neither remark, nor remark-html do. As previously mentioned, only at compilation one can create source maps.

> https://github.com/sidorares/pugify

That does things to [JavaScript embedded in Pug](https://github.com/sidorares/pugify/blob/6c7a9941d2b3eac1bab36b5e89324cfc8d6c5bf4/index.js#L86). Not to the HTML. I still believe HTML does not support source maps.

> Anyways I understand it's a quite unpopular feature and it's possible to live without it :)

Yes, for me it is, that’s why I suggest something external :+1:
