### ISSUE TITLE
Support for tables with single column with dashes?

### ISSUE THREAD

**Issue by mishak87** [wooorm/remark#179]
I am not sure if it is legal but gitbook supports it. Am I missing some setting?
```sh
remark --tree-out <<MD
| a | b |
| -- |
| c | d |
MD
```
```json
{
  "type": "root",
  "children": [
    {
      "type": "paragraph",
      "children": [
        {
          "type": "text",
          "value": "| a | b |\n| -- |\n| c | d |",
```

**Comment by wooorm** [comment]
Thanks for the Q!

Neither GitHub nor markdown-it (which mimics GH-style tables) support that, so keeping it out of the core seems logical. Rather, user-land would be the best place for this. If you’re so inclined, a plug-in which interfaces with the parser, would use what is known in remark as a [**tokenizer**](https://github.com/wooorm/remark/blob/master/doc/remarkplugin.3.md#function-tokenizereat-value-silent).
