### ISSUE TITLE
Bug: remark processing files twice

### ISSUE THREAD

**Issue by kgryte** [wooorm/remark#180]
Command:

``` bash
remark --config-path ./etc/.remarkrc.js --ignore-path ./etc/.remarkignore --use remark-lint README.md
```

Versions:

```
"remark": "^4.2.2"
"remark-lint": "^3.2.1"
```

While debugging why certain `.remarkrc.js` rules were being ignored, found the following output:

```
README.md 100
100
README.md undefined
80
# Beep

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
file.md
      4:446  warning  Line must be at most 100 characters  maximum-line-length
      4:446  warning  Line must be at most 80 characters   maximum-line-length

⚠ 2 warnings
```

My `remark` configuration is as follows:

```
{ plugins: 
   { lint: 
      { reset: true,
        'blockquote-indentation': 2,
        'checkbox-character-style': [Object],
        'checkbox-content-indent': true,
        'code-block-style': 'fenced',
        'definition-case': true,
        'definition-spacing': true,
        'emphasis-marker': '*',
        'fenced-code-flag': true,
        'fenced-code-marker': '`',
        'file-extension': 'md',
        'final-definition': true,
        'final-newline': true,
        'hard-break-spaces': true,
        'heading-increment': true,
        'link-title-style': '"',
        'list-item-bullet-indent': true,
        'list-item-content-indent': true,
        'list-item-indent': 'space',
        'list-item-spacing': true,
        'maximum-heading-length': 40,
        'maximum-line-length': 100,
        'no-auto-link-without-protocol': true,
        'no-blockquote-without-caret': true,
        'no-consecutive-blank-lines': false,
        'no-duplicate-definitions': true,
        'no-duplicate-headings': true,
        'no-emphasis-as-heading': true,
        'no-file-name-articles': true,
        'no-file-name-consecutive-dashes': true,
        'no-file-name-irregular-characters': true,
        'no-file-name-mixed-case': true,
        'no-file-name-outer-dashes': true,
        'no-heading-content-indent': true,
        'no-heading-indent': true,
        'no-heading-punctuation': true,
        'no-html': false,
        'no-inline-padding': true,
        'no-literal-urls': true,
        'no-missing-blank-lines': true,
        'no-multiple-toplevel-headings': false,
        'no-shell-dollars': false,
        'no-shortcut-reference-image': true,
        'no-shortcut-reference-link': true,
        'no-table-indentation': true,
        'no-tabs': true,
        'no-undefined-references': true,
        'no-unused-definitions': true,
        'ordered-list-marker-style': '.',
        'rule-style': '___',
        'strong-marker': '_',
        'table-cell-padding': 'padded',
        'table-pipe-alignment': true
      }
   }
}
```

I inserted a `console.log` at [line 77](https://github.com/wooorm/remark-lint/blob/eb82bd9f984790e39cc11319992a7d04796bf8c1/lib/rules/maximum-line-length.js#L77) in the `remark-lint` rule `maximum-line-length`. During the apparent first run, the `maximum-line-length` value is correctly printed. During the second run, the value is `undefined` and the default value of `80` is used.

Any idea why this is happening?

**Comment by wooorm** [comment]
This happens because you specify the 'lint' plug-in twice, first using 'use', second in the configuration file.

We recently added a sentence about this in the README: "We now run the below command without the -u remark-lint since our .remarkrc includes the lint plugin.", but as you still ran into it, could you let me know if and how I could make this clearer?

**Comment by kgryte** [comment]
@wooorm Thanks for the response. Missed that line in the `remark-lint` README.

This, however, implies that I cannot pass `remark` a configuration and then choose which plugins are run when using command-line option flags; i.e., I cannot have a master configuration file and then toggle plugins just using `--use`.

I am also unsure as to when running the same plugin twice is useful. Is there a particular use case where I would want to use the plugin with a configuration and also again, during the same run, with possibly different settings? I suppose if I was interactively wanting to augment the file configuration (but not override). I feel, however, that the override use case would be more common.

Thanks again for the response.

**Comment by wooorm** [comment]
Yes, indeed. If you need logic, you can of course expose different configuration by using a JavaScript module (`.remarkrc.js`). Or, you can toggle configuration files by naming them differently and specifying them in separate calls (`remark -c a.js; remark -c b.js`).

For reasoning: an example is `remark-slug`, which is also `use`d by other plug-ins to ensure heading identifiers are fresh in several phases of the process: just before checking links, just before compiling to HTML, &c. For `remark-lint`, it could be used with different configurations as you mention, e.g., at the start checking for some rules, and at the end checking some other rules.

Does that help?

**Comment by wooorm** [comment]
I’m closing this as this “bug” is fixed, but feel free to still respond here / chat on Gitter

**Comment by kgryte** [comment]
Fair enough. The command-line docs for `--use` could probably be more explicit in terms of when using the option in conjunction with a configuration file is warranted or not.
