### ISSUE TITLE
Question: extension command-line option concats, rather than replaces. Why?

### ISSUE THREAD

**Issue by kgryte** [wooorm/remark#181]
Currently, the `--ext` command-line option concatenates provided extensions with an internal list (see [src](https://github.com/wooorm/remark/blob/fc5e502cfc908db401394337548131cc739e777f/lib/cli/cli.js#L309)). While I can understand the intent to allow users to add their own extensions, the current API does not allow specifying an exclusive set of extensions (using the `--ext` option). For instance, I may only want `remark` to search for files ending in `*.md` and not `'*.markdown'`, `'*.mkd'`, `'*.mkdn'`, `'*.mkdown'`, and `'*.ron'`. 

*A priori*, I would expect that, when I set a command-line option, that is the value which is used. From a third party perspective, setting `--ext md` does not convey what happens under the hood. A third party who sees the invocation must be aware that `--ext` merely extends a hidden list, rather than restricts the universe of allowed files.

**Comment by wooorm** [comment]
Yup, it does (P.S. there’s also [in-depth docs](https://github.com/wooorm/remark/blob/master/doc/remark.1.md#-e---ext-extensions) and [man pages](https://github.com/wooorm/remark/blob/master/man) :) ).

I understand that it’s a bit weird, however, those extensions signify what classifies a markdown file. The whole process of traversing the file system is based more on directories and ignoring those.

How did you run into this? Why would one specify a directory\* to remark, have it search it for markdown files, and not expect it to return some markdown files? And if that happens, why are ignores not enough?

Thanks!


\* It’s also possible specify files and globs to files of course, but those are not affected by `--ext`.

**Comment by kgryte** [comment]
I am aware of the docs and man pages.

I ran into this because I expected one behavior and experienced another. My thinking was that I could give a directory without having to provide a glob with an extension and could, instead, specify the particular extension for which I wanted `remark` to search.

**Comment by wooorm** [comment]
It’s in [unified-args](https://github.com/wooorm/unified-args) already, and will come to remark hopefully this weekend!

**Comment by kgryte** [comment]
@wooorm Awesome! Thanks!

**Comment by wooorm** [comment]
Included in the new `remark-cli` package!
