### ISSUE TITLE
Split core and cli into separate packages

### ISSUE THREAD

**Issue by azu** [wooorm/remark#182]
Hi, It is a suggestion that split core(parse/generator) and cli into separate packages.

This is commonly approach.

- [Babel](https://github.com/babel/babel "Babel") has [babel-core](https://github.com/babel/babel/tree/master/packages/babel-core "babel-core") and [babel-cli](https://github.com/babel/babel/tree/master/packages/babel-cli "babel-cli").
- Many JavaScript AST tools exist as separated package.
    - [ternjs/acorn: A small, fast, JavaScript-based JavaScript parser](https://github.com/ternjs/acorn)
    - [estools/escodegen: ECMAScript code generator](https://github.com/estools/escodegen)
    - [jquery/esprima: ECMAScript parsing infrastructure for multipurpose analysis](https://github.com/jquery/esprima)
    - [eslint/espree: An Esprima-compatible JavaScript parser](https://github.com/eslint/espree)

### Pros

- Fast installation
  - Currently, remark depended on native module like [chokidar](https://github.com/paulmillr/chokidar "chokidar") for `--watch` #51 
  - Build time of native module is large :(
  - We want to use remark as pure JS parser/generator, but install native module.
- Separated responsibility
  - That's why ESLint have not `--watch` option: https://github.com/eslint/eslint/issues/2513

### Cons

- Maintenance cost
	- That's why Babel apply [monorepo](https://github.com/babel/babel/blob/master/doc/design/monorepo.md "monorepo") approach.

### My Proposal

- Split `stringify.js` and `parse.js` to into separate package like `remark-core`
- `remark` package contain cli that is the same as it is now.

What do you think about this?

**Comment by wooorm** [comment]
Yes!  And, funnily, I’m already working on this, moving to a mono repo:

```
packages/remark/ # basically `unified().use(parse).use(stringify)`
packages/remark-parse/
packages/remark-stringify/
packages/remark-cli/ # CLI, which is a few options for `unified-cli`, which I’m currently writing tests for.
```

**Comment by azu** [comment]
Cool 👍

**Comment by wooorm** [comment]
Done in 8108fe54e04640dda119aad366d70e6edf2602f1! You can now install `remark-cli` for the CLI, `remark` for the API, for mix and match with `unified`, `remark-parse`, and `remark-stringify`.
