### ISSUE TITLE
"extends" in .remarkrc

### ISSUE THREAD

**Issue by kachkaev** [wooorm/remark#183]
Hey guys,

I discovered `remark` after having some experience with `eslint` and I quite like the fact that these two tools share some ideas. Because of the resulting similarity, I expected to see one feature in  `remark`, but I could not find it. It is about `.remarkrc` inheritance.

In `eslint` people often rely on some shared config, such as [one by airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb). It is possible create your own base config on top of something common and use it in all new projects:

```bash
cd new-project
npm install --save eslint-config-my-super-rules
```
`new-project/.eslintrc`:
```json
{
  "extends": "my-super-rules"
}
```

When a team decides to follow a new `.eslint` rule, someone just updates `eslint-config-my-super-rules` (a central node module) and then others just `npm update` inside the dependent projects. This way it is much easier to stay organized in a team because no eslint rules are project-specific.

The same approach could be used with remark linter (or other remark plugins):
```bash
cd new-project
npm install --save remark-config-my-super-rules
```
`new-project/.remarkrc`:
```json
{
  "extends": "my-super-rules"
}
```
When all remark-linter rules are shared across multiple projects, there is less debate on how `*.md` should look like in each individual case. If a team is not happy with the current state of things, a rule is added or removed in a _single source of truth_ for remark and everyone is happy again.

How feasible would be to add something like this to remark?

**Comment by wooorm** [comment]
Coool! I like this idea, and I definitely see it included in the future.

Now, ESLint is a linter, whereas remark is more like esprima, acorn, or others. With that in mind, do you see the whole `.remarkrc` extend other configs?

```json
{
  "extends": "my-super-rules",
  "output": true
}
```

Or, just the plugins:

```json
{
  "plugins": {
      "extends": "my-super-rules",
  },
  "output": true
}
```

Or, just remark-lint:

```json
{
  "plugins": {
    "lint": {
      "extends": "my-super-rules"
    }
  },
  "output": true
}
```

Note that something like this already works, by using `--config-path ./node_modules/my-super-rules/index.js`, but that’s not very nice of course.

**Comment by kachkaev** [comment]
Hey @wooorm, glad that you like the suggestion!

I haven't been using `remark` for anything but linting so far, so I'm afraid it's difficult to recommend what sort of inheritance would be better. Thanks for the `--config-path` tip!

There's probably one more thing one can do in the meantime: to simply make `my-project/.remarkrc` a symlink to `my-project/node_modules/remark-config-my-super-rules/.remarkrc`. A symlink will perfectly fit into a git repo, so a cloned working copy should work right away after `git clone` and `npm install` ([unless you are on Windows](http://stackoverflow.com/questions/5917249/git-symlinks-in-windows)). Looks like a solution with a symlink will suit me for now, because it is also compatible with Atom's linter for markdown files.

**Comment by evilebottnawi** [comment]
@wooorm I think it would be cool to be able `extend` in all levels (config, plugins, setting - rules for plugins)

**Comment by wooorm** [comment]
Small update: I’ve decided to go with `presets` instead, similar to how [Babel presets](https://babeljs.io/docs/plugins/#pluginpresets-options) work.

Here’s an example using presets:

```js
{
  "presets": [
    "lint-recommended" // remark-preset-lint-recommended
  ],
  // completely optional overwriting of options:
  "plugins": {
    "lint": {
      "bullet": "*"
    }
  }
}
```

Where `remark-preset-lint-recommended` could look as follows:

```js
{
  "plugins": {
    "lint": {
      "finalNewline": true,
     // ...
    }
  }
}
```

If the user installed `remark-lint`, it’ll use that, otherwise the one in the preset is used!

Thus, they’re basically sharable configs, but the mental model of Babel fits better than ESLint.

For now I’m writing some tests and stuff. Hope to do a proper release this/next week.

**Comment by Francois-Esquire** [comment]
Hi @wooorm has this been implemented?

**Comment by wooorm** [comment]
Locking and hiding to keep the discussion clean.
You are responding on a 6 year old, solved, issue. See my last comment, and the commit that closed this, for the answer “has this been implemented”.
This has since changed a bit. Presets can be passed everywhere just like plugins can.
For the latest on presets, see the API docs: https://github.com/unifiedjs/unified#preset.
