### ISSUE TITLE
Behaviour of "remark ." depends on the number of existing files

### ISSUE THREAD

**Issue by kachkaev** [wooorm/remark#184]
I linked the same version of remark with the same config to two projects and noticed that the  behaviour of `remark .` was different. In one case I was getting a plain linting report as expected and in another one the contents of `README.md` ended up in STDOUT as well.

It turned out that the reason for this little inconsistency was in the way `remark` entered pipeline mode (saw a mentioning of this in [lib/cli/file-pipeline/stdout.js](
https://github.com/wooorm/remark/blob/master/lib/cli/file-pipeline/stdout.js)). If the number of files to work with is one, output turns on.

It might be reasonable to ignore the pipeline mode not only when there are several files to process, but also if the working set of one file is a result of a search (e.g. `.`). Hope that it is never that case that the search results need to be piped, so changing the behaviour will not cause any BC issues.

Meanwhile I'll be just creating `DUMMY.md` in addition to `README.md` if that's the only `.md` in a project to avoid the problem.

Cheers!

**Comment by wooorm** [comment]
Yup, you’re right. It’s also documented in [`-o, --output`](https://github.com/wooorm/remark/blob/master/doc/remark.1.md#-o---output-path), and there’s an option to turn that behaviour off: [`--no-stdout`](https://github.com/wooorm/remark/blob/master/doc/remark.1.md#--no-stdout).

To rephrase you, more accurately: the report is written to **stderr**(4), and the formatted contents is written to **stdout**(4).

Reformatting is quite an important part of remark. See it this way: when possible, the reformatted document is written. Either to the file-system (`--output`) or to **stdout**(4).

I’ve just open up another issue (see above) on the soon-to-be relevant repo, slightly rephrased. I’ll close this here, but you track how things happen over there!

**Comment by kachkaev** [comment]
Awesome, thank you!
