### ISSUE TITLE
HTML nodes are parsed to AST inconsistently

### ISSUE THREAD

**Issue by yaycmyk** [wooorm/remark#185]
We have spoken before re: HTML strings, and I like your methodology of splitting the HTML element away from its children such that the children can be processed for md markup.

However, remark only seems to actually do that for inline layout tags like `<span>`, `<strong>`, etc. As soon as a block-level tag like `<div>` is included, remark passes right over it and will not split the HTML as expected.

For a more specific example:

```js
remark.parse('<span>**Hello**</span>')
```

results in

```json
{
    "type": "root",
    "children": [
        {
            "type": "paragraph",
            "children": [
                {
                    "type": "html",
                    "value": "<span>",
                    "position": {
                        "start": {
                            "line": 1,
                            "column": 1,
                            "offset": 0
                        },
                        "end": {
                            "line": 1,
                            "column": 7,
                            "offset": 6
                        },
                        "indent": []
                    }
                },
                {
                    "type": "strong",
                    "children": [
                        {
                            "type": "text",
                            "value": "Hello",
                            "position": {
                                "start": {
                                    "line": 1,
                                    "column": 9,
                                    "offset": 8
                                },
                                "end": {
                                    "line": 1,
                                    "column": 14,
                                    "offset": 13
                                },
                                "indent": []
                            }
                        }
                    ],
                    "position": {
                        "start": {
                            "line": 1,
                            "column": 7,
                            "offset": 6
                        },
                        "end": {
                            "line": 1,
                            "column": 16,
                            "offset": 15
                        },
                        "indent": []
                    }
                },
                {
                    "type": "html",
                    "value": "</span>",
                    "position": {
                        "start": {
                            "line": 1,
                            "column": 16,
                            "offset": 15
                        },
                        "end": {
                            "line": 1,
                            "column": 23,
                            "offset": 22
                        },
                        "indent": []
                    }
                }
            ],
            "position": {
                "start": {
                    "line": 1,
                    "column": 1,
                    "offset": 0
                },
                "end": {
                    "line": 1,
                    "column": 23,
                    "offset": 22
                },
                "indent": []
            }
        }
    ],
    "position": {
        "start": {
            "line": 1,
            "column": 1,
            "offset": 0
        },
        "end": {
            "line": 1,
            "column": 23,
            "offset": 22
        }
    }
}
```

But

```js
remark.parse('<div>**Hello**</div>')
```

results in:

```json
{
    "type": "root",
    "children": [
        {
            "type": "html",
            "value": "<div>**Hello**</div>",
            "position": {
                "start": {
                    "line": 1,
                    "column": 1,
                    "offset": 0
                },
                "end": {
                    "line": 1,
                    "column": 21,
                    "offset": 20
                },
                "indent": []
            }
        }
    ],
    "position": {
        "start": {
            "line": 1,
            "column": 1,
            "offset": 0
        },
        "end": {
            "line": 1,
            "column": 21,
            "offset": 20
        }
    }
}
```

I think it would be very beneficial to have both situations output the same structure of AST, so we're not losing out on the richness afforded by processing the inner text.

**Comment by wooorm** [comment]
Hey @yaycmyk, thanks for reaching out!

Although I understand where you’re coming from (it would be helpful when parsing HTML to virtual DOMs), I don’t think it should be in the core of markdown. Rather, it could be dangerous for non-HTML use cases.

Take the following markdown:

```js
<div>**Hello**</div>

<span>**Hello**</span>
```

Here’s how [markdown.pl](http://daringfireball.net/projects/markdown/dingus) renders it:

```html
<div>**Hello**</div>

<p><span><strong>Hello</strong></span></p>
```

Here’s how GitHub renders it (span sanitised):

```html
<div>**Hello**</div>

<p><strong>Hello</strong></p>
```

Here’s how [markdown-it](https://markdown-it.github.io):

```html
<div>**Hello**</div>
<p><span><strong>Hello</strong></span></p>
```

Here’s how [CommonMark](http://spec.commonmark.org/dingus/) renders it:

```html
<div>**Hello**</div>
<p><span><strong>Hello</strong></span></p>
```

As you can see, all implementations allow inline HTML and markdown to live next to each other. But they don’t allow the same for blocks of HTML.

If **remark** would allow that, it would produce different output from other markdown to HTML compilers (and we can’t have that). I can see two ways remark *could* support this, but I don’t like them:

a) `<div>` as html node, `Hello` as text node inside strong node, `</div>` as HTML node. This means plug-ins will walk into this node and change or lint things, and it will produce wrong output (`<strong>` where no strong should be created). There also needs to be a new wrapper node, as `paragraph` can’t be used either.

b) `<div>` as html node, `**Hello**` as text node, `</div>` as HTML node. There also needs to be a new wrapper node, plus the text will be escaped when compiling, which will also produce wrong output when compiling to anything non-HTML.

Semantically, there’s a difference in block-level HTML and inline-level HTML spans, and in how they’re handled. Changing that for this use case results in changes for other, non HTML use cases, and I can only imagine bad results.

Note that these two examples look similar, but the block-level example also stands for whole blocks of `<script>`s and `<iframe>`s, and note that:

```md
<div>

A *paragraph*

</div>
```

Is parsed as `<div>`, a paragraph with emphasis, and `</div>`.

---

If you’re going to transform markdown to a (virtual) DOM, you’ll have to:

1. Ignore HTML;
2. Use `innerHTML` / `dangerouslySetInnerHTML`;
3. Parse HTML.

If you’re going with the latter, you’ll have to deal with this problem and I don’t believe adding your proposed feature makes it easier.

---

P.S. I’d love to help fix this problem though (outside of core) so do let me know if you need help or wan’t to chat!
