### ISSUE TITLE
stringify option to not convert < to &lt;

### ISSUE THREAD

**Issue by jayvdb** [wooorm/remark#187]
`4 < 5` is valid syntax, and it is one of the features of markdown that markup like `&lt;` is avoided unless necessary.

By default remark is converting `<` to `&lt;` , and I cant see an option to disable it.

I am guessing there is a good reason to encode the `<` , probably for compatibility with some systems, but in my case I know the target renderrer can handle `<`, and I know my target humans dont want to see `&lt;`.

**Comment by wooorm** [comment]
Could you show me an extracted sample, and how you’re using remark?

**Comment by jayvdb** [comment]
Here is my first attempt at seeing what voodoo remark can do with a fairly
broken md file; im just using the cli without any options

https://github.com/jayvdb/PocketEuler/commit/d878045f9bbbb1378f72810e18929eec8fa76c2c

Im impressed with how much it did do, but it only fixed a few of many
broken renderrings, and is injecting these entities and replacing * with _
where backslashing the * would be better.

**Comment by jayvdb** [comment]
I am invoking remark on the command line and piping the output to a file.

I expect the less than symbol to not be emitted as a ml entity.

I have already looked at the config options, and not found one that fixes this.

**Comment by wooorm** [comment]
Please provide exactly what input you’re passing, what output you got, what you expected, and *how* you’re running remark.

**Comment by jayvdb** [comment]
https://github.com/jayvdb/PocketEuler/blob/auto-remark/.travis.yml#L6

```bash
$ npm install -g remark-cli
$ remark ./README.md > ./README.md.new
$ diff -u ./README.md ./README.md.new
```

Results:
https://travis-ci.org/jayvdb/PocketEuler/builds/137394968

First example of undesirable conversion:
https://travis-ci.org/jayvdb/PocketEuler/builds/137394968#L394

**Comment by wooorm** [comment]
Thanks! 👍 

No, there’s no way to get around that. The reason the encoding is that it’s very easy for opening angle brackets (`<`) to end up starting HTML or auto links.

I suggest wrapping all of the inline math-like constructs in the document as `code` spans (with ticks around them). That ensures they’re not seen as other syntaxes. Plus, I personally perceive code spans in text as more readable when there’s lots of switching between prose and non-prose.
