### ISSUE TITLE
Number at end of sentence in middle of paragraph

### ISSUE THREAD

**Issue by jayvdb** [wooorm/remark#188]
remark considers the `24.` at the beginning of the line, in the following block, to be the start of a list .

```markdown
As 12 is the smallest abundant number, 1 + 2 + 3 + 4 + 6 = 16, the
smallest number that can be written as the sum of two abundant numbers is
24. By mathematical analysis, it can be shown that all integers greater
than 28123 can be written as the sum of two abundant numbers.
```

https://travis-ci.org/jayvdb/PocketEuler/builds/137394968#L593

There is a little variation in how markdown tools handle this scenario.

pandoc only treats it as a list start for `commonmark` and `markdown_github`.

Note this comes from https://github.com/imsky/PocketEuler/blob/3be130e8bd327b5040ad546f2f76700aa4a20c30/README.md#problem-23 (and as seen there, github isnt one of the parsers that barfs on this)

Not surprising remark-lint believes it is a block node:

https://travis-ci.org/jayvdb/PocketEuler/builds/137690082#L439

However, remark does this whether or not `commonmark` is enabled.

What makes this more interesting is that when I change `24.` to `24\.`, to avoid the list start, remark removes the `\` .

As there is two variation in this scenario, perhaps default behaviour could be for remark to emit markdown that is stable for both interpretations? (e.g. put the 24 on the preceding line)

**Comment by wooorm** [comment]
Thanks, 👍 I’ve fixed it. So, in short, bullets in paragraphs are messy. Check the commit message for some insight :)
