### ISSUE TITLE
Undesirable blank line added

### ISSUE THREAD

**Issue by jayvdb** [wooorm/remark#190]
With input

```
Extra sentence. Extra sentence. Extra sentence. Extra sentence to hit 80. To
illustrate:
- abc
- def
- ghi
- jkl
```

The result has an extra blank line added:

```
Extra sentence. Extra sentence. Extra sentence. Extra sentence to hit 80. To

illustrate:

*   abc
*   def
*   ghi
*   jkl
```

The first line length doesnt impact the result; I've made it long to show why the word `illustrate` is on the next line.

**Comment by wooorm** [comment]
Curious!

**Comment by wooorm** [comment]
Found it, the paragraph tokenizer saw the next line as a setext heading (`foo\n---`), which it of course isn’t!

**Comment by jayvdb** [comment]
It looks like this hasnt been released yet.

**Comment by wooorm** [comment]
Indeed, I’m going to bundle it with GH-192. But npm can depend on [GitHub SHAs as well](http://stackoverflow.com/questions/14187956/npm-install-from-git-in-a-specific-version), so I suggest to use that for now.
