### ISSUE TITLE
Support for custom HTML block elements

### ISSUE THREAD

**Issue by Mr0grog** [wooorm/remark#192]
Now that web components are a thing (and just in general for XML anyway), it would be nice to support arbitrary block elements. For example, if I have markdown like this:

```markdown
A paragraph

<example>
  - A
  - List
  - Of
  - Things
</example>
```

I'd expect to get:

```html
<p>A paragraph</p>
<example>
  <ul>
    <li>A</li>
    <li>List</li>
    <li>Of</li>
    <li>Things</li>
  </ul>
</example>
```

But instead I get:

```html
<p>A paragraph</p>
<p><example></example></p>
<ul>
  <li>A</li>
  <li>List</li>
  <li>Of</li>
  <li>Things</li>
</ul>
```

These elements are always parsed as inline, due to the whitelist here: https://github.com/wooorm/remark/blob/master/packages/remark-parse/lib/block-elements.json

But, if I'm reading the spec right, this should at least be allowed in commonmark: https://github.com/jgm/CommonMark/blob/master/spec.txt#L8531-L8534 (although the accompanying example is inline, so it's not extraordinarily clear). [Markdown-it](https://github.com/markdown-it/markdown-it) supports this, at least.

Is there a case where Remark really needs to ensure that an element is or is not a block? Could the whitelist simply be eliminated? Otherwise, maybe the whitelist could be inverted and made into a blacklist—elements that can only appear in inline form?

If none of that is workable and we can't have arbitrary block-level elements, it would at least be nice to expose the whitelist on the parser so that plugins can modify it. I can do this in a really terrible way now, but it's pretty ugly and very brittle (it depends on how NPM winds up processing the dependencies):

```js
var blockElements = require('remark-parse/lib/block-elements.json');
blockElements.push('example');
remark().process(someText);
```

(FWIW, I am running into this issue in an actual project I’m working on for a client.)

**Comment by wooorm** [comment]
@Mr0grog 👍 I like this, and see no reason not to implement it.

However, say you provide a list of tag-names to see as block-level elements, should it be *instead* of the internal list, or joined with the internal list?

Also, I don’t get your results with commonmark or [markdown-it](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22A%20paragraph%5Cn%5Cn%3Cexample%3E%5Cn%20%20-%20A%5Cn%20%20-%20List%5Cn%20%20-%20Of%5Cn%20%20-%20Things%5Cn%3C%2Fexample%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D), either.

**Comment by wooorm** [comment]
@Mr0grog Ping!

**Comment by Mr0grog** [comment]
Sorry for the slow reply! I’ve been traveling and am just now catching up.

> Also, I don’t get your results with commonmark or markdown-it, either.

My fault—I took my specific case and generalized without testing 😓  Markdown-it appears to require blank lines around the block element, so this works where my previous example did not:

```md
A paragraph

<example>

  - A
  - List
  - Of
  - Things

</example>
```

If it helps, my actual/original use case is a language-switcher for code samples:

    This code prints some text:
    
    <code-example name="Printing Text">
    ```js
    console.log('Some text!');
    ```​
    
    ```java
    System.out.println("Some text!");
    ```​
    
    ```go
    import "log"
    log.Println("Some text!")
    ```​
    </code-example>

> However, say you provide a list of tag-names to see as block-level elements, should it be instead of the internal list, or joined with the internal list?

I definitely think this should be joined with the internal list. Or at the very least, that’s what the easy path should do. I can’t imagine wanting to make `<section>` behave like an inline element would be a common desire.
