### ISSUE TITLE
Remark emits syntax that renders as links on github 

### ISSUE THREAD

**Issue by jayvdb** [wooorm/remark#193]
1617a6c04b altered the way links were parsed to better support github flavour, but the following behaviour also occurred before that.

The backslash is necessary in the following to prevent it being a link in github flavoured syntax.

```markdown
For 1 ≤ k ≤ 55, s[k] = [100003 − 200003k + 300007k^3] \(modulo 1000000) − 500000.
```

However remark removes the `\` to emit

```markdown
For 1 ≤ k ≤ 55, s[k] = [100003 − 200003k + 300007k^3] (modulo 1000000) − 500000.
```

which renders as:

For 1 ≤ k ≤ 55, s[k] = [100003 − 200003k + 300007k^3] (modulo 1000000) − 500000.

The problem does not occur if the space is removed; the following is not modified by remark, as it knows the backslash is necessary

```markdown
For 1 ≤ k ≤ 55, s[k] = [100003 − 200003k + 300007k^3]\(modulo 1000000) − 500000.
```

But that means the whitespace is lost.

pandoc also defaults to removing the `\` in `\(`, instead adding `\` before the `[`, rewriting

```markdown
For 1 ≤ k ≤ 55, s[k] = [100003 − 200003k + 300007k^3] \(modulo 1000000) − 500000.
```

to be

```markdown
For 1 ≤ k ≤ 55, s\[k\] = \[100003 − 200003k + 300007k\^3\] (modulo
1000000) − 500000.
```

Which is probably too much backslashing, bit it renders correctly on github:

For 1 ≤ k ≤ 55, s\[k\] = \[100003 − 200003k + 300007k\^3\] (modulo
1000000) − 500000.

If we push pandoc output into remark, it outputs the following (which is a different bug?)

```markdown
For 1 ≤ k ≤ 55, s\[k] = \[100003 − 200003k + 300007k\\^3] (modulo 1000000) − 500000.
```

The following markdown is accepted and emitted by remark (unmodified) and render ok on github, so that is a workaround.

```markdown
For 1 ≤ k ≤ 55, s[k] = \[100003 − 200003k + 300007k^3] (modulo 1000000) − 500000.
```

**Comment by jayvdb** [comment]
Presumably the fix for this issue is for remark to convert the markdown mentioned at the top of this issue using ` \(` into the markdown at the bottom of the issue that uses `\[` to prevent the link.  If you agree, I'd like to have a go at this change.

**Comment by wooorm** [comment]
Thanks, fixed!

**Comment by jayvdb** [comment]
Afaics, this is not entirely fixed.  The remaining issue appears to be that input

`For 1 ≤ k ≤ 55, s[k] = [100003 − 200003k + 300007k^3] \(modulo 1000000) − 500000.`

comes out without any backslash, as

`For 1 ≤ k ≤ 55, s[k] = [100003 − 200003k + 300007k^3] (modulo 1000000) − 500000.`

which renders as

For 1 ≤ k ≤ 55, s[k] = [100003 − 200003k + 300007k^3] (modulo 1000000) − 500000.

**Comment by wooorm** [comment]
Whoops, I believe it’s fixed now for real! Could you try out f958a708658833a5476fef9b7f8a45a7523ed6fd?

**Comment by jayvdb** [comment]
No, in the above scenario, remark is still removing the `\` from the `\(`, and not re-adding a `\` anywhere so the result is the same.

**Comment by wooorm** [comment]
@jayvdb Are you sure you’re on that commit: f958a708658833a5476fef9b7f8a45a7523ed6fd?

```sh
cat example.md
```

Yields:

```txt
For 1 ≤ k ≤ 55, s[k] = [100003 − 200003k + 300007k^3] \(modulo 1000000) − 500000.
```

...and:

```sh
remark example.md
```

Yields:

```txt
For 1 ≤ k ≤ 55, s[k] = [100003 − 200003k + 300007k^3] \(modulo 1000000) − 500000.
```

(as in, I’m getting the escape)

**Comment by jayvdb** [comment]
I am so sorry, I didnt notice that was on a branch.   Yes, that commit fixes the problem I was seeing, and I cant see any new problems.

A unrelated and cosmetic issue

`For 56 ≤ k ≤ 4000000, s[k] = [s[k−24] + s[k−55] + 1000000] (modulo 1000000) − 500000.`

is now emitted as

`For 56 ≤ k ≤ 4000000, s[k] = [s\[k−24\] + s\[k−55\] + 1000000](<modulo 1000000>) − 500000.`

Are the inner `\[` really necessary? -- im guessing that the `\]` are enough to ensure any sensible parser will correctly determine the intended link..?  Any parser that believes that it should link the inner `[k−55\] + 1000000]` either has a silly bug believing that a `[` in a link can be anything other than a normal character, or the parser is processing the MD in reverse, and the author is nuts.  But alas, what you are emitting is likely to be the most resilient, and this case could be written off as "ugly in ; slightly more ugly out".
