### ISSUE TITLE
math support

### ISSUE THREAD

**Issue by jayvdb** [wooorm/remark#196]
remark doesnt consider `$...$` to be math, so `$a*b*c$` is revised to be `$a_b_c$` if emphasis is configured to be `_`.

**Comment by wooorm** [comment]
`$...$` isn’t markdown. This is beyond the core of this project. Luckily, remark has plug-ins. I suggest creating a [transformer](https://github.com/wooorm/unified#function-transformernode-file-next) which modifies the syntax tree, or a plug-in which integrates with the [markdown parser in remark](https://github.com/wooorm/remark/tree/master/packages/remark-parse#extending-the-parser).
Another source of information is the section on [“Creating plugins”](https://github.com/wooorm/remark/blob/master/doc/plugins.md#creating-plugins), and there’s always [Gitter](https://gitter.im/wooorm/remark) for help.

**Comment by jayvdb** [comment]
It is a default extension to markdown in pandoc.  And part of MultiMarkdown 3 and 4, and many others.  I can appreciate it understanding the contents is beyond scope, but being able to add `$` as an inline fencing symbol (in addition to `\` would be helpful)

**Comment by jayvdb** [comment]
Sorry that should be 
> (in addition to \` would be helpful)

**Comment by jayvdb** [comment]
As an example, to use LaTeX for the case that I've been using for several of the bugs

`For $1 ≤ k ≤ 55, s_k = [100003 − 200003k + 300007k^3] (\text{modulo } 1000000) − 500000$.`

remark emits

`For $1 ≤ k ≤ 55, s_k = [100003 − 200003k + 300007k^3] \(\\text{modulo } 1000000) − 500000$.`

which is invalid.

It looks like maybe this can be done by enabling `commonmark`, which includes `$` in the list in `escapes.json`.

**Comment by jayvdb** [comment]
No, that didnt seem to work. :/  And I cant find a test case which covers this scenario.

**Comment by jayvdb** [comment]
My workaround is to insert `\hspace{0pt}` between the `]` and `(`, so Github doesnt render it as a link, and remark doesnt detect it as a link or try to escape `]` and `(`.

`For $1 ≤ k ≤ 55, s_k = [100003 − 200003k + 300007k^3] \hspace{0pt} (\text{modulo } 1000000) − 500000$.`

remark is still changing `\` to `\\` within the `$..$` , so another workaround will be needed, but at least now remark isnt fiddling with the brackets.

`For $1 ≤ k ≤ 55, s_k = [100003 − 200003k + 300007k^3] \\hspace(0px} (\\text{modulo } 1000000) − 500000$.`

**Comment by wooorm** [comment]
@jayvdb Thanks for the research. However, I still think this should not be in the core, rather, a plug-in.

**Comment by AStupidBear** [comment]
+1 for being in the core

**Comment by jayvdb** [comment]
@wooorm , what would be very useful is if remark core allowed `$...$` to be configured (especially wrt `remark-cli`) as a literal that should not be modified (i.e. mangled).

That is a fairly generic capability, and would allow any other other markdown hacks to also be configured to be passed through remark unmodified.

For math, this is actually a very good solution, as there are now lots of browser plugins and JS libraries which will do the render on the client side.

**Comment by Rokt33r** [comment]
@jayvdb I've made`remark-math` which recognize `$` as a math.
