### ISSUE TITLE
Let plugins return a Promise to indicate asynchronousity instead of the done() function

### ISSUE THREAD

**Issue by sindresorhus** [wooorm/remark#197]
That would let sync plugins not have to call `done()` and async can just return a Promise.

Instead of:

```js
module.exports = (ast, file, language, done) => {
	done();
};
```

It could be:

```js
module.exports = (ast, file, language) => {

};
```

For sync plugins.

And:

```js
module.exports = (ast, file, language) => {
	return new Promise(resolve => {
		setTimeout(resolve => 2000);
	});
};
```

For async plugins.

**Comment by wooorm** [comment]
That should already be possible! The docs could use some help though, but here’s the related [section](https://github.com/wooorm/unified#function-transformernode-file-next)!

**Comment by wooorm** [comment]
From your code it seems like this is a remark-lint rule? They are a little weird :( They don’t yet work there...

**Comment by sindresorhus** [comment]
Yes, a `remark-lint` rule.

**Comment by wooorm** [comment]
Ah, then it’s already solved :)
