### ISSUE TITLE
Tables containing Chinese are formatted wrong 

### ISSUE THREAD

**Issue by QMonkey** [wooorm/remark#200]
### Test case

test.md

``` markdown
| abcddef     | head2 |
| ------- | ----- |
| 中文      |    dddd  |
```

Command:

``` bash
remark test.md
```
### Expected output

![screenshot_20160810_105841](https://cloud.githubusercontent.com/assets/3848542/17540663/6f452554-5eea-11e6-96ac-c13eee2d8c17.png)
### Observed output

![screenshot_20160810_105932](https://cloud.githubusercontent.com/assets/3848542/17540672/8582fde6-5eea-11e6-9afb-1be4b32bea4e.png)
### Supplementary info

``` bash
$ remark -v
remark: 5.0.1, remark-cli: 1.0.0
```

**Comment by QMonkey** [comment]
It seems like that CJK (Chinese, Japanese and Korean) characters are traditionally classed into [fullwidth](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms) characters which are encoded in a DBCS (double byte character set).
Any other functions like [stringWidth](https://github.com/sindresorhus/string-width) should be use to calculate the display width of table cell, rather than 'string.length'.

**Comment by wooorm** [comment]
😧 

Darn! Thanks for letting me know. That indeed has to do with fullwith characters.

However, I don’t think ANSI sequences should be stripped (which `string-width` does).

Also: what about emoji (which are [unfixable](https://github.com/sindresorhus/string-width/issues/2), but still…)

**Comment by sindresorhus** [comment]
> However, I don’t think ANSI sequences should be stripped (which string-width does).

Of course they should. ANSI escapes have no impact on the width.

**Comment by wooorm** [comment]
> Of course they should. ANSI escapes have no impact on the width.

On a terminal they don’t, but when written to a file and opened in an editor it’s different. The control character doesn’t impact width whereas the stuff after the bracket does (e.g., `\u001b` has no width, `[1m` does).

I don’t know much about this, but it seems like [wcwidth](https://github.com/timoxley/wcwidth) is a better fit. From what I gather that’s similar to how much width is used when e.g. rendering text files?

**Comment by wooorm** [comment]
P.S. Appreciate the input! :)

**Comment by sindresorhus** [comment]
Why would you print ANSI escape codes to a Markdown table? That doesn't make much sense.

**Comment by wooorm** [comment]
Haha yeah, it’s really weird. It probably wouldn’t hurt to have that code in there.

Also: any reason why `string-width` counts control characters ([example](https://tonicdev.com/56cf1c0dd554190d00185383/57af7386b055491400ef35de))?

**Comment by sindresorhus** [comment]
I made it ignore control characters (https://github.com/sindresorhus/string-width/commit/d367d294556310009e1e2e62dd30420413134265).

As for `zero width space`, it does take up space in the terminal:

<img width="352" alt="screen shot 2016-08-13 at 22 00 40" src="https://cloud.githubusercontent.com/assets/170270/17645291/6b925cba-61a1-11e6-8d6c-286de9d1a879.png">

**Comment by sindresorhus** [comment]
So indeed probably better to use `wcwidth` for this case.

**Comment by sindresorhus** [comment]
Does zero width space take up space for you too?

**Comment by wooorm** [comment]
`\u200B` takes up one character on my terminal (e.g. `cat`ting files). But when opening in Atom / TextEdit / etc. the zero-width spaces don’t take up any character space.

For some reason my shell doesn’t allow unicode `\u` chars though, that’s probably a difference between my Bash and your Zsh (?), so I couldn’t properly compare that.

Another problem: `wcwidth` counts `\t` as `0`, `string-width` counts them as `1`, but how they’re displayed depends on the actual column they’re at of course. What’s best? 😕

**Comment by sindresorhus** [comment]
> Another problem: wcwidth counts \t as 0, string-width counts them as 1, but how they’re displayed depends on the actual column they’re at of course. What’s best?

I would say 1, because they're never 0 in width, right?
