### ISSUE TITLE
Migrating from mdast...

### ISSUE THREAD

**Issue by digitalmoksha** [wooorm/remark#202]
@wooorm, I've been using mdast for awhile to generate an ast with source information.  I recently ran across a bug in the table support, and I've been wanting to upgrade to the latest for awhile.

Now that you've moved it to remark, i'm not exactly sure how to build what I need (a js file for use in browser).

Previously I was using `mast.min.js` and `mdast-range.min.js`, and then using `md.parse` and `md.run`

Sorry this is a basic question, but what's the best way to generate the js file needed for use in a browser?

**Comment by wooorm** [comment]
Oh, glad you’re updating! 👍 A lot has changes though, so there will be difference you’ll run into.
I suggest using the [Gitter channel](https://gitter.im/wooorm/remark) for more question-y things!

There are prebuilt releases for each version over on [GH Releases](https://github.com/wooorm/remark/releases), so you could use those.

Alternatively, and I think better, you could setup something like [browserify](https://github.com/substack/node-browserify) or [webpack](https://github.com/webpack/webpack) to do the building.

How those actually work is beyond the scope of this project though, but I think it’s really worth the time to learn any of these two!

Does that help?

**Comment by digitalmoksha** [comment]
Thanks, that does help.

What do you use to execute your build-bundle.js script?

**Comment by wooorm** [comment]
It's in node, so 'node scrip/build-bundle'.

However, that script is longer than it needs to be: it's OK for this project, but I normally use something like: 'browserify input.js > output.js', and 'esmangle output.js > output.min.js'.

**Comment by digitalmoksha** [comment]
Cool, thank you
