### ISSUE TITLE
Access to untrimmed value strings

### ISSUE THREAD

**Issue by davidtheclark** [wooorm/remark#207]
I think it would be useful to have access to untrimmed versions of a node's `value`.

For example, I'm building a tool that parses markdown then feeds the code blocks into a linter. In order to know accurate line numbers for linting errors *if the code block has empty lines at its beginning*, I need to know how many empty lines there *are* at the beginning. Right now I don't think there's enough information in the AST for me to know that (am I wrong?).

**Comment by wooorm** [comment]
Interesting stuff. Could you expand more on why you want that? What are you trying to do exactly?

For a currently actionable solution: You could do a little reparsing of code-blocks as well (use `node.position.start.offset`)

**Comment by davidtheclark** [comment]
Let's say I have this markdown (pretending ''' = \`\`\`):

```
Some text.

'''css



.foo {}

'''

Some other text.
```

I end up with this code node:

```js
{ type: 'code',
  lang: 'css',
  value: '.foo {}',
  position: 
   Position {
     start: { line: 7, column: 1, offset: 54 },
     end: { line: 12, column: 4, offset: 75 },
     indent: [ 1, 1, 1, 1, 1 ] } }
```

I'm linting that block of CSS, and the linter is warning me that I have an empty rule. But how do I know what line in the file this empty rule is actually no? I can see that the CSS code block starts at line 7 and ends at line 12. But because `value` is trimmed I don't know which of those lines contains `.foo {}`, right? It could be any of them?

**Comment by wooorm** [comment]
@davidtheclark That’s a very valid point, thanks for bringing it up!

I’m kinda resisting adding it to the AST though: from my experience on [remark-lint](https://github.com/wooorm/remark-lint), having positions of *anything* would be useful (as in, a CST would be useful), but the downsides of that are that CSTs are hard to handle for other use-cases.

I’m wondering, you suggest changing the core/tree, but would it also work if there’s a utility outside of the core that gives access to the raw value?

**Comment by davidtheclark** [comment]
> would it also work if there’s a utility outside of the core that gives access to the raw value?

Yeah, that sounds fine. Either the raw value the `before` and `after` bits that got trimmed (that's how PostCSS handles this, for example).

**Comment by wooorm** [comment]
Ok, hold on a sec, I’m planning a solution.

**Comment by wooorm** [comment]
OK, with [`unist-util-source`](https://github.com/wooorm/unist-util-source), you’re able to get the exact source of a node (regardless of whether it’s in nested block-quotes or lists or whatnot).

As you’re just checking for `code` nodes with a `lang`, you can split the resulting value on newlines, and ignoring the first and last lines (fences), you’ll get the precise value you’re looking for!

It isn’t perfect, but it’ll work for now.
I’m not really a fan of adding `before` / `after` props though. Not sure whether I wan’t to go down the road of trying to make a CST out of an AST. If you run into the need of a proper CST, could you open an issue over on [MDAST](https://github.com/wooorm/mdast)?
