### ISSUE TITLE
Option to prevent URL from being enclosed in angle brackets?

### ISSUE THREAD

**Issue by sebastienbarre** [wooorm/remark#208]
Great work on unified/remark, just started playing with it.
I was wondering if there was an easy way (or an option I missed) to prevent URLs from being automatically enclosed in angle brackets?

e.g.
```
- http://foo.com
```
is parsed as Markdown, then stringified back to:
```
- <http://foo.com>
```
but since these brackets are optional in this case (since there are no spaces, are parens, etc), I'd rather keep it simple without the brackets. Can I control this behavior?

Thanks

**Comment by wooorm** [comment]
@sebastienbarre Hi, thanks for checking it all out, I appreciate that :)

No, that’s currently not possible. Reason: literal URLs do not work in most places, for example, they don’t work on CommonMark or pedantic/Gruber markdown.

If you’d really want this, you can always [integrate with the compiler](https://github.com/wooorm/remark/tree/master/packages/remark-stringify#extending-the-compiler). Or create a PR that does this here.

**Comment by wooorm** [comment]
I’m fine with adding this if someone puts a PR up, or creates an external plugin for it, but it’s not on my TODO list!
