### ISSUE TITLE
Help formatting Free Software Magazine

### ISSUE THREAD

**Issue by mercmobily** [wooorm/remark#210]
I am the owner of Free Software Magazine. We had a huge server crash. I am 99.9% finished eradicating the article database from the ancient Drupal system, and have converted everything to a static file. (http://www.freesoftwaremagazine.com -- it's not styled yet... the priority right now is getting the data back up!)

The problem I have is that I have Markdown like this:

    What about Android?
    
    <div class="textbox">
    <h2>But Tony, didn't you love Ubuntu?</h2>
    <div class="textbox-contents">
    Yes, I still **absolutely** love Ubuntu; 
    * One
    * Two
    * Three
    </div>
    </div>
    Blah blah

I need `remark` to:

* Leave the HTML as it is (this is already happening)
* Actually *format* the contents of the DIV (this is not happening)

 At the moment, I am doing:

var remark = require('remark');
var html = require('remark-html');

    ...
    fileData.contents = remark().use(html).process( fileData.contents );
    ....

With the PHP version of Markdown, I could add something the the HTML:

    <div class="textbox-contents" markdown=1>

And the contents would be interpreted. Is there any way I could do that here?

Thank you!

**Comment by wooorm** [comment]
Hi Tony, thanks for raising an issue.

Ouch, that sounds bad!

The way to do it currently is by changing the markdown and adding blank lines between the raw HTML and the markdown:

```diff
 What about Android?

 <div class="textbox">
 <h2>But Tony, didn't you love Ubuntu?</h2> 
 <div class="textbox-contents">
+
 Yes, I still **absolutely** love Ubuntu; 
 * One
 * Two
 * Three
+
 </div>
 </div>
 Blah blah
```

Structuring the markdown is your best bet, as it works in CommonMark as well!


Does that help?

**Comment by mercmobily** [comment]
It did! It did! I have finally closed this task!!! Thank you! I am glad to see that Markdown got some real specs in the last few years. Thank you for writing this module!

**Comment by wooorm** [comment]
Great to hear, thanks!
