### ISSUE TITLE
listItemIndent with string value vs number value

### ISSUE THREAD

**Issue by BarryThePenguin** [wooorm/remark#212]
Setting up my `.remarkrc` and noticed that the following config gave me tabs for `listItemIndent` instead of spaces

```json
{
  "output": true,
  "settings": {
    "listItemIndent": 1
  },
  "plugins": {
    "lint": {
      "list-item-indent": "space"
    }
  }
}
```

setting `"listItemIndent": "1"` fixed the issue.

also using `"list-item-indent": "1"` in `settings` doesn't work either

**Comment by wooorm** [comment]
I made `1` as a number work!

**Comment by BarryThePenguin** [comment]
:tada: best, love your work.
