### ISSUE TITLE
'./block-elements' not found.

### ISSUE THREAD

**Issue by Catx7** [wooorm/remark#215]
Please check  
 `remark/packages/remark-parse/lib/defaults.js`
** `blocks: require('./block-elements'),`**

**Comment by wooorm** [comment]
This is an issue with webpack. https://github.com/webpack/webpack/issues/184 seems to solve it.

**Comment by Catx7** [comment]
works only if I use:
require('./block-elements.json')

**Comment by wooorm** [comment]
Ah, sorry, you also need this: https://github.com/wooorm/hast-util-sanitize/pull/1#issuecomment-238027874
