### ISSUE TITLE
remark: command not found when using remark-cli

### ISSUE THREAD

**Issue by gotofritz** [wooorm/remark#219]
Hi. I was trying to use stylelint-config-standard, which uses remark-cli, and I when I tried to run `npm test` I got `"remark: command not found"`.

I explored a bit and it looks like npm doesn't like the way the path for bin in the remark-cli's package.json is set (it just needs to start with "./"). I will submit a PR.

**Comment by wooorm** [comment]
How weird, are you sure about this?
I’ve used this on Node 4 extensively, and never ran into any problems!

**Comment by gotofritz** [comment]
Positive, it happens with 4.2.6 for me

**Comment by wooorm** [comment]
Funky: I just cloned `stylelint-config-standard`, and did the following:

```sh
nvm use 4.2.6
cd stylelint-config-standard
npm i
```

...and everything went fine!

Could you show me how I can reproduce this problem?

**Comment by gotofritz** [comment]
Mmm. A restart seems to have automagically fixed everything O_o

Apologies for wasting your time

**Comment by wooorm** [comment]
No problem, thanks for checking!

**Comment by sidvenu** [comment]
I am facing this issue currently. It says `remark: command not found` when I try running it.

**Comment by wooorm** [comment]
@sidvenu Please open new issues and fill in the issue template.
