### ISSUE TITLE
Ordered List after List will be List

### ISSUE THREAD

**Issue by pastak** [wooorm/remark#222]
Hi. I want to parse markdown text includes list and ordered list.

## example input

```
- item
- item
- item

1. item
1. item
1. item
```

## expect result

```
- item
- item
- item

1. item
2. item
3. item
```

### result

```
-   item
-   item
-   item

-   item
-   item
-   item
```

Why is this result? And can I solve it?

**Comment by wooorm** [comment]
What settings do you use?

**Comment by pastak** [comment]
I set no options. Only exec `% ./node_modules/.bin/remark < input.md`

**Comment by ohtake** [comment]
I run into the same issue.
Workarounds would be:

* inserting two blank lines between lists, or
* enable CommonMark option
