### ISSUE TITLE
Support definition lists syntax

### ISSUE THREAD

**Issue by KyleAMathews** [wooorm/remark#225]
ala https://github.com/fletcher/MultiMarkdown/wiki/MultiMarkdown-Syntax-Guide#definition-lists

This would be nice to have

**Comment by wooorm** [comment]
Definitely! It’s a good idea for a plugin that [integrates with the parser](https://github.com/wooorm/remark/tree/master/packages/remark-parse#extending-the-parser)! If someone wants to make it I’d love to give advice!

It’s not high on my TODO list though, so I’m closing it here.
