### ISSUE TITLE
Adding a block tokenizer

### ISSUE THREAD

**Issue by Rokt33r** [wooorm/remark#232]
I'm now trying to make math block plugin of remark.  So I had to extend the tokenizer with `$$`. But, I found a problem.

This would be parsed as intended.
```
Math block

$$
\alpha + \beta = \gamma
$$
```

But, this would NOT be parsed.
```
Math block
$$
\alpha + \beta = \gamma
$$
```

I've already found the reason why it works like the above. The paragraph tokenizer of remark eats `$$` also as a part of paragraph.

```js
    if (
      tokenizers.thematicBreak.call(self, eat, subvalue, true) ||
      tokenizers.atxHeading.call(self, eat, subvalue, true) ||
      tokenizers.fencedCode.call(self, eat, subvalue, true) ||
      tokenizers.blockquote.call(self, eat, subvalue, true) ||
      tokenizers.html.call(self, eat, subvalue, true)
    ) {
      break;
    }
```

>https://github.com/wooorm/remark/blob/master/packages/remark-parse/lib/tokenize/paragraph.js#L93-L101

The real problem comes here. **I cannot inject my rule to this loop**.

I've already checked the modified code below. It seems to work well.

```js
    if (
      tokenizers.thematicBreak.call(self, eat, subvalue, true) ||
      tokenizers.atxHeading.call(self, eat, subvalue, true) ||
      tokenizers.fencedCode.call(self, eat, subvalue, true) ||
      tokenizers.math.call(self, eat, subvalue, true) || // Injecting the custom rule `math`
      tokenizers.blockquote.call(self, eat, subvalue, true) ||
      tokenizers.html.call(self, eat, subvalue, true)
    ) {
      break;
    }
```

For now, I have to replace whole code of the paragraph tokenizer. I think this would be a quite bad practice.
Is there any way to expose this rule? Like `self.paragraphAfterMethods = ['thematicBreak', 'atxHeading', ...]`

**Comment by wooorm** [comment]
You’re right! I added `interruptParagraph` to fix that!

**Comment by Rokt33r** [comment]
It looks awesome! Thanks for the fast response! 💯 💯 💯

**Comment by wooorm** [comment]
Haven’t released it yet though, I’ll try to do some more issues first!
