### ISSUE TITLE
How to specify filename/id?

### ISSUE THREAD

**Issue by unional** [wooorm/remark#245]
I want to process multiple files. The example:

```js
remark().use(lint).use(html).process('## Hello world!', function (err, file) {
  console.error(report(err || file));
  console.log(String(file));
});
```
generates
```sh
        1:1  warning  Missing newline character at end of file  final-newline
   1:1-1:16  warning  First heading level should be `1`         first-heading-level
   1:1-1:16  warning  Don’t add a trailing `!` to headings      no-heading-punctuation
```
where `1:1` is the `name`. I want to change it to a meaningful name such as `index`, `page1`, etc.

**Comment by wooorm** [comment]
Hi!

You can pass in a [`vfile`](https://github.com/vfile/vfile).

More info over on [unified](https://github.com/unifiedjs/unified#processorprocessfilevalue-done).
