### ISSUE TITLE
Getting remark to leave this TOC Markdown untouched

### ISSUE THREAD

**Issue by JetStreamVelocity** [wooorm/remark#246]
# Description

## Background:

I am using the [Jekyll Documentation Theme](https://github.com/tomjohnson1492/documentation-theme-jekyll) for a project. It uses a piece of Markdown for setting up the table of contents on a page.

```
* Table of Contents
{:toc}
```

# Problem:
Need to get Remark (in use as an [atom-beautify](https://github.com/Glavin001/atom-beautify/) plugin)  to leave it untouched. The beautified code doesn't play well with [Jekyll](https://jekyllrb.com/). Is there a way to tell ```Remark``` not to reformat this?

I have played with the settings but cannot get it to work. I have posted [some debug information](https://gist.github.com/JetStreamVelocity/eec80d1daf1d541bec39a1c785148328). If more information would help, I am happy to try to obtain it, but might need some guidance on obtaining it. 

Is this a bug? If not, any workaround?

PS: I am new to Markdown

# Input Before Beautification

This is what the code looked like before:

```
* Table of Contents
{:toc}
```

# Expected Output

The beautified code should have remained like this:

```
* Table of Contents
{:toc}
```

# Actual Output

The beautified code actually looked like this:

Using Remark:
```
-   Table of Contents
    {:toc}
```

**Comment by wooorm** [comment]
Hi @JetStreamVelocity!

Jekyll stuff isn’t part of markdown. It’s often used as a template, and when compiled with data, results in HTML or markdown. Remark expects markdown, so it treats the list (`'* '`) as a list, and the contents (`'Table of Contents\n{:toc}'`) as a value in that.

However, I’m wondering, why do you even use a list? Why `* Table of Contents\n{:toc}` instead of `Table of Contents\n{:toc}`? Or even `## Table of Contents\n\n{:toc}`?

**Comment by JetStreamVelocity** [comment]
Hi @wooorm, thanks for looking into this.

I tried both your suggestions above. And fiddled some more. None worked. Like I mentioned, I'm a newbie in this area. It appeared for some reason the syntax expected this to be a list. So I went exploring further and came across the ```kramdown``` documentation.

I found that this TOC syntax is part of the ```kramdown``` feature set. [Automatic “Table of Contents” Generation](https://kramdown.gettalong.org/converter/html.html#toc) has a more detailed explanation - and indeed, it expects a list.

Would it be right to say the ``kramdown`` flavour is not supported? 

Worth considering this as a feature request then, please?

**Comment by wooorm** [comment]
Hi @JetStreamVelocity, sorry for the delay!

Have you tried this code?

```md
# Contents

{:toc}

# H1 header

## H2 header
```

It may just work. If not, could you provide more info why not?

> Would it be right to say the kramdown flavour is not supported?

Correct, kramdown’s extensions are not supported out of the box.

> Worth considering this as a feature request then, please?

I’m not interested in adding support for that. However, everything is possible through [plugins](https://github.com/wooorm/remark/blob/master/doc/plugins.md). Plugins do still need someone to champion and create them though.
There’s also a a pretty good [ToC plugin](https://github.com/wooorm/remark-toc) out there already!

Finally, I’m closing this as this is not something that should go in this project. Plugins could do it, but someone needs to create them first.
