### ISSUE TITLE
behavior change for footnotes

### ISSUE THREAD

**Issue by probablyup** [wooorm/remark#247]
I was upgrading some remark dependencies for `markdown-to-jsx` and came across an unexpected behavior change: the caret is now being preserved in footnotes.

Previously this markdown:

```md
foo[^abc] bar

[^abc]: Baz baz
```

Would strip out the caret when making the footnote link. However now it seems to be preserved in the output.

**Comment by wooorm** [comment]
Hi Evan! :wave:

Passing options to `.parse` (and `.stringify`, `.process`) no longer work (https://github.com/unifiedjs/unified/issues/24).

Based on this example and current setup in markdown-to-jsx, the following diff highlights the changes needed to make it work with unified@7.0.0

```diff
 var unified = require('unified');
 var parser = require('remark-parse');
 
 var markdown = `foo[^abc] bar
 
 [^abc]: Baz baz
 `;
 
 var options = {
   footnotes: true,
   gfm: true,
   position: false,
 }
 
 var tree = unified()
-  .use(parser, options)
+  .data('settings', options)
+  .use(parser)
   .parse(markdown);
 
 console.dir(tree, {depth: null});
```

**Comment by probablyup** [comment]
Thanks!
