### ISSUE TITLE
Atx heading are being prepended by a backslash

### ISSUE THREAD

**Issue by ChrisRast** [wooorm/remark#250]
Hello,

On some documents, after being parsed by `remark-cli` some headings are being modified with a backslash:
```
# Data-table content

Displays content as a 2 column table. Mostly used for `overviewContent` than `editContent`.

## Table of content

1.  [Properties](#properties)
2.  [Example](#example)

## Properties

...
```
becomes 
```
# Data-table content

Displays content as a 2 column table. Mostly used for `overviewContent` than `editContent`.

\## Table of content

1.  [Properties](#properties)
2.  [Example](#example)

## Properties

...
```
 My command:
`remark {dir} -oq --rc-path {somePath}`.

The `.remarkrc` file contains this: 
```
{
	"plugins": [
		"remark-preset-lint-recommended",
		"remark-preset-lint-consistent",
		["remark-lint-list-item-content-indent", false]
	]
}
```

Any idea why?

NOTE: This happens with any level of heading, and without any consistency on the preceding or following content.

**Comment by wooorm** [comment]
That’s weird! I’m not getting any problems!

Could you:

1. Create a repository that reproduces the problem for you? Containing all the needed files, exact versions of packages, and a the command you need to get this problem?
2. Provide info on which OS you’re running? Which Node? etc.

**Comment by ChrisRast** [comment]
Hello,
You'll find here the repo: https://github.com/ChrisRast/remark-parsing-errors
Do you need any other infos?
Thank you

**Comment by wooorm** [comment]
Hi, thanks for that, I’ve found the issues.

The issue here is that it’s not a space between the `##` and `Table of content`. Rather, it’s a non breaking space (`\u00A0`, NO-BREAK SPACE). As you can see, GitHub [doesn’t render it as a heading either](https://github.com/ChrisRast/remark-parsing-errors/blob/master/docs/atx-heading.md)!

If you use a normal space, everything in `atx-heading.md` works :+1:

**Comment by ChrisRast** [comment]
Wow, indeed!
No idea why there was one here...
Thanks!

**Comment by wooorm** [comment]
Sure no problem :)
