### ISSUE TITLE
Converting remark to es modules

### ISSUE THREAD

**Issue by probablyup** [wooorm/remark#252]
Is this something you'd be interested in community involvement from?

I'd love to work on it, as it would help people using the library in the browser thanks to es module treeshaking capabilities in webpack 2, etc, potentially smaller bundles 👍

**Comment by wooorm** [comment]
Hi Evan, thanks for the issue!

To be honest, I’m not a fan of “ES2020”. Yup, it’s coming to JS everywhere, so the code will change sometime in the future, but I want to wait for stuff to stabilise first. I think support in Node is very important.

Of course, `require` isn’t standard JS and doesn’t work everywhere, but at least it’s very stable, and I don’t feel modules is stable enough to make the jump.

P.S. I experienced rewriting libraries with CoffeeScript: I’d rather rewrite my stuff as few times as possible :)
P.P.S. I’ve added you to `unifiedjs` and `wooorm/remark`, if you want you can work on branches to rewrite `remark-parse` and `unified` as modules so we can discuss the results of tree shaking! (let me know if I need to add you to more repo’s)

**Comment by Rokt33r** [comment]
I want to help this too!

**Comment by wooorm** [comment]
Oh btw I’m very open to more people chiming in!

**Comment by probablyup** [comment]
Awesome, thank you Titus! I'll play around in a branch and do some size comparisons.

**Comment by wooorm** [comment]
@probablyup @Rokt33r Any news for this folks?

**Comment by probablyup** [comment]
Not yet, I've been away for a week and a deadline at work before that.
It'll probably be gradual work for me.

**Comment by wooorm** [comment]
:+1: Do let me know if you need help!

**Comment by Rokt33r** [comment]
I'll start working this on this weekend.

**Comment by wooorm** [comment]
Closing for now, I’m still super open to it, if it actually makes things smaller!
