### ISSUE TITLE
Can remark add a space before and behind a **abc**/_abc_/`abc`?

### ISSUE THREAD

**Issue by mgdreamingstar** [wooorm/remark#255]
Want to use atom-beautify to make Chinese characters and English words more readable:
这是一个**abc**例子.
这是一个_abc_例子.
这是一个`abc`例子.

Hope to get:
这是一个 **abc** 例子.
这是一个 _abc_ 例子.
这是一个 `abc` 例子.

**Comment by wooorm** [comment]
That’s a feature of markdown, not a bug: e.g., there’s cases like this `**re**mark` (**re**mark).

But you could of course [create a plugin](https://unifiedjs.github.io/create-a-plugin.html) for that!
