### ISSUE TITLE
What is linkReference actually ?

### ISSUE THREAD

**Issue by paranoidjk** [wooorm/remark#258]
The original markdown is below:
```md
[ABC]
```
remark will parse it to: 

```js
{
  "type": "root",
  "children": [
    {
      "type": "paragraph",
      "children": [
        {
          "type": "linkReference",
          "identifier": "abc",
          "referenceType": "shortcut",
          "children": [
            {
              "type": "text",
              "value": "ABC",
              "position": {
                "start": {
                  "line": 1,
                  "column": 2,
                  "offset": 1
                },
                "end": {
                  "line": 1,
                  "column": 5,
                  "offset": 4
                },
                "indent": []
              }
            }
          ],
          "position": {
            "start": {
              "line": 1,
              "column": 1,
              "offset": 0
            },
            "end": {
              "line": 1,
              "column": 6,
              "offset": 5
            },
            "indent": []
          }
        }
      ],
      "position": {
        "start": {
          "line": 1,
          "column": 1,
          "offset": 0
        },
        "end": {
          "line": 1,
          "column": 6,
          "offset": 5
        },
        "indent": []
      }
    }
  ],
  "position": {
    "start": {
      "line": 1,
      "column": 1,
      "offset": 0
    },
    "end": {
      "line": 1,
      "column": 6,
      "offset": 5
    }
  }
}
{
  "content": [
    "article",
    [
      "p",
      "[abc]"
    ]
  ],
  "meta": {}
}
```

but IMO, should `[ABC]` just be a plain text ?

**Comment by wooorm** [comment]
A link reference is a reference to a link defined before or after: `[alpha][]`, `[alpha][]`, and `[bravo][alpha]` all refer to a link defined as `[alpha]: http://example.com`.

There’s one caveat though, and that is that `[alpha]` is rendered as plain-text (so actually `[alpha]`) based on whether there is or isn’t a definition, whereas `[alpha][]` and `[bravo][alpha]` both render as links even if there’s no definition.

Does that help?

**Comment by paranoidjk** [comment]
If i understand correctly, I have a single markdown file, which content is `[alpha]`, should remark parse it to plain text ?

As i mentioned above, remark parse  `[alpha]` as linkReference, I think this may be a bug?

**Comment by wooorm** [comment]
No, that’s a feature.

Say we have the following file:

```markdown
[foo] and [bar].

[foo]: example.com
```

Both `[foo]` and `[bar]` are references to links, even though `[bar]` is not defined.

When compiling to HTML, `[bar]` is compiled as plain text, whereas `[foo]` is compiled as a link. This is a feature of the compiler.

For more info, see the similar issue GH-209.

**Comment by paranoidjk** [comment]
Even though i am much agree with https://github.com/wooorm/remark/issues/209#issuecomment-247794212, but i am ok with  current situation.

I decided to handle linkReference  in our compiler. https://github.com/benjycui/mark-twain/pull/20/files

Thanks for your explanation.

**Comment by wooorm** [comment]
Great, thanks for using remark!
