### ISSUE TITLE
Footnotes: two consecutive footnoteReference are parsed as linkReference

### ISSUE THREAD

**Issue by vhf** [wooorm/remark#259]
Hey!

I think the behaviour I'm encountering is a bug. Here is some Markdown I `reparse`d with `footnotes: true` as only option:

```markdown
a[^foo]

a[^foo][^foo]

a[^foo][^foo][^foo][^foo]

a[^foo][^foo][^foo][^foo][^foo]

[^foo]: MyNote
```

I end up with this AST:

```
root[5] (1:1-11:1, 0-100)
├─ paragraph[2] (1:1-1:8, 0-7)
│  ├─ text: "a" (1:1-1:2, 0-1)
│  └─ footnoteReference (1:2-1:8, 1-7) [identifier="foo"]
├─ paragraph[2] (3:1-3:14, 9-22)
│  ├─ text: "a" (3:1-3:2, 9-10)
│  └─ linkReference[1] (3:2-3:14, 10-22) [identifier="^foo"][referenceType="full"]
│     └─ text: "^foo" (3:4-3:8, 12-16)
├─ paragraph[3] (5:1-5:26, 24-49)
│  ├─ text: "a" (5:1-5:2, 24-25)
│  ├─ linkReference[1] (5:2-5:14, 25-37) [identifier="^foo"][referenceType="full"]
│  │  └─ text: "^foo" (5:4-5:8, 27-31)
│  └─ linkReference[1] (5:14-5:26, 37-49) [identifier="^foo"][referenceType="full"]
│     └─ text: "^foo" (5:16-5:20, 39-43)
├─ paragraph[4] (7:1-7:32, 51-82)
│  ├─ text: "a" (7:1-7:2, 51-52)
│  ├─ linkReference[1] (7:2-7:14, 52-64) [identifier="^foo"][referenceType="full"]
│  │  └─ text: "^foo" (7:4-7:8, 54-58)
│  ├─ linkReference[1] (7:14-7:26, 64-76) [identifier="^foo"][referenceType="full"]
│  │  └─ text: "^foo" (7:16-7:20, 66-70)
│  └─ footnoteReference (7:26-7:32, 76-82) [identifier="foo"]
└─ footnoteDefinition[1] (9:1-9:15, 84-98) [identifier="foo"]
   └─ paragraph[1] (9:9-9:15, 92-98)
      └─ text: "MyNote" (9:9-9:15, 92-98)
```

As you can see, the subtle bug is that instead of parsing `[^foo][^bar]` as two consecutive `footnoteReference`s, they are parsed as a `linkReference`s just like we'd parse `[my website][reference] … [reference]: foo`.

I attempted a few things to fix this but it doesn't seem possible without modifying a bunch of fixtures.

The easiest way I found for my fixtures to work was to replace this line: <https://github.com/wooorm/remark/blob/858e94b2fcc5fb17a1d59a96aab2283e44baba11/packages/remark-parse/lib/tokenize/reference.js#L125>
with
```js
if ((self.options.footnotes && type !== T_FOOTNOTE) && character === C_BRACKET_OPEN) {
```

**Comment by wooorm** [comment]
Interesting, what’s your opinion on the following examples?

```markdown
1. [foo][bar]
2. [^foo][bar]
3. [foo][^bar]
4. [^foo][^bar]
```

...what should be what?

**Comment by vhf** [comment]
```markdown
1. [foo][bar]
2. [^foo][bar]
3. [foo][^bar]
4. [^foo][^bar]
```

1. Link with reference (should become a link if there's a `[bar]: ` somewhere providing the actual link)
1. If there's a `[^foo]: ` footnote, then it'd become a footnoteReference followed and the rest of the line `[bar]…` gets parsed further down (`[^foo][bar][baz]` would, with what I'm suggesting for this point, become a footnoteReference followed by a linkReference provided that both `foo` and `baz` are present for these)
1. `[^bar]` is a footnoteReference, if `[foo]` cannot get parsed with what's in front of it then it'd be the litteral `[foo]`
1. footnoteReference footnoteReference, like: _"Mickey Mouse has been seen eating cheese numerous times.¹²³"_ (`…times.[^1][^2][^3]`)

Does it make sense?

**Comment by wooorm** [comment]
Yup, makes sense!

I’d like to add though that `[alpha]`, `[alpha][]`, and `[bravo][alpha]` are all link references to `alpha: https://example.com`, in the tree, whether the definition is defined or not! You can find more about that in GH-258.

Does this change your previous suggestions?

**Comment by vhf** [comment]
Oh nice, I didn't know that. No it doesn't change my suggestion 👍

**Comment by wooorm** [comment]
Want to work on a PR?

**Comment by vhf** [comment]
If it's easy for you, I'd rather let you patch this. I spent an hour on this yesterday and although I found how to achieve this for my settings (gfm), I couldn't figure out how to achieve this behavior for all existing fixtures.

I can spend more time on it if you prefer a PR though :)
