### ISSUE TITLE
Support .remarkrc.js

### ISSUE THREAD

**Issue by ndelangen** [wooorm/remark#260]
Current behavior is such that the `.remarkrc` file must be a json file.

I'd like to be able to just write javascript as config. This allows for comments, composition and re-use.

I'm requesting support for a `.remarkrc.js` file.

**Comment by wooorm** [comment]
Have you tried it? It should work!

**Comment by ndelangen** [comment]
It does, work! 
Am I missing a documentation site where such things are documented?

**Comment by wooorm** [comment]
Where did you find out about `.remarkrc`? Because the `.remarkrc.js` is mentioned in the [CLI docs](https://github.com/wooorm/remark/tree/master/packages/remark-cli)!

**Comment by ndelangen** [comment]
I think I found it in an example project, not in documentation.
