### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by kentcdodds** [wooorm/remark#261]
This is an enabling package and I want to say thank you for building it. I'm building something that I think is pretty neat and this package is making it possible. So thank you very much! 🥇 💯

**Comment by wooorm** [comment]
Thanks for reaching out Kent, I appreciate it a lot!
What are you working on? Feel free to chat on Gitter or DM on Twitter to talk!

👋

**Comment by kentcdodds** [comment]
Check out [this weirdness](https://github.com/kentcdodds/glamorous-website/blob/master/other/CONTRIBUTING_DOCUMENTATION.md#special-syntax) 🙃

**Comment by wooorm** [comment]
Fancy! I can’t completely grasp all that’s going on in a few minutes though, but for now I already have a tip you may find useful!

Next to remark, you can also use [rehype](https://github.com/wooorm/rehype), specifically for HTML, and then later transform to React with [`rehype-react`](https://github.com/rhysd/rehype-react). You could do all that “safely” without needing to resort to `dangerouslySetInnerHTML`.

Now, I’m not entirely sure how to do the funky code-block to component handling, but `rehype-react` [has a `components`](https://github.com/rhysd/rehype-react#options) option, that maps (custom?) tag-names to React components, which may help?

**Comment by kentcdodds** [comment]
Cool! I'll look into it! Thanks!
