### ISSUE TITLE
Option to turn off indentedCode tokenizer

### ISSUE THREAD

**Issue by davidtheclark** [wooorm/remark#267]
I'm not sure if this is a good idea or not, but thought I'd brought it up since it seemed important for my use.

I am processing Markdown in such a way that I'd love to prevent the parser from interpreting indented blocks as code — just paragraphs will do.

I found that I can accomplish this with the following:

```js
delete remarkParse.Parser.prototype.blockTokenizers.indentedCode;
```

Because the `Parser` is part of the public and documented API, maybe this is safe, and the preferable way to turn off this feature.

If you don't consider it safe, do you think it would be helpful to other remark users to expose an option to turn off this feature?

**Comment by wooorm** [comment]
Yes, it’s the safe thing to do! I think we could make it easier for people to use by [publishing this plugin idea I had recently](https://github.com/wooorm/remark/issues/248#issuecomment-296392249), or to add docs on this, or to change the API?

**Comment by davidtheclark** [comment]
Created a PR (#271) for the quickest solution — documentation — since it seems to me this might be a rare use case.
