### ISSUE TITLE
A third level header breaks tables and lists.

### ISSUE THREAD

**Issue by AmarOk1412** [wooorm/remark#268]
Hi!

I think we found a bug with headers:

# First test

## Input
```
notATitle
- item 1
- item 2
```

## Actual result:
```
<h3>notATitle</h3>
<ul>
<li>item 2</li>
</ul>
```

## Expected:
```
<p>notATitle</p>
<ul>
<li>item 1</li>
<li>item 2</li>
</ul>
```

# Second test

## Input
```
a|b
---|---
c|d
```

## Actual result:
```
<h3>a|b</h3>
<p>c|d</p>
```

## Expected:
```
<table>
<thead>
<tr>
<th>a</th>
<th>b</th>
</tr>
</thead>
<tbody>
<tr>
<td>c</td>
<td>d</td>
</tr>
</tbody>
</table>
```

Note, if you remove the second item from the first test or if you replace `a|b` by `a |b` for the second test, the result is correct.

I use only these plugins: **remark-parse**, **rehype-stringify**, **remark-rehype**

**Comment by wooorm** [comment]
Weird, thanks for the detailed info! And hi! 👋 

Could you show me how you’re using remark / rehype / plugins?

**Comment by AmarOk1412** [comment]
Sure! I use this file: `https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-heading-trailing-spaces/__tests__/index.js` (without `.use(plugin)` and inputs described in my first post)

So, something like:

```
import {readdirSync as directory, readFileSync as file} from 'fs'
import {join} from 'path'
import ava from 'ava'
import unified from 'unified'
import reParse from 'remark-parse'
import rehypeStringify from 'rehype-stringify'
import remark2rehype from 'remark-rehype'

const base = join(__dirname, 'fixtures')
const specs = directory(base).reduce((tests, contents) => {
  const parts = contents.split('.')
  if (!tests[parts[0]]) {
    tests[parts[0]] = {}
  }
  tests[parts[0]][parts[1]] = file(join(base, contents), 'utf-8')
  return tests
}, {})

const entrypoints = [
  '../dist',
  '../src',
]

entrypoints.forEach(entrypoint => {
  const plugin = require(entrypoint)

  ava('with plugin', t => {
    const {contents} = unified()
      .use(reParse)
      .use(remark2rehype)
      .use(rehypeStringify)
      .processSync(specs['headings'].fixture.replace(/·/g, ' '))

    t.deepEqual(contents, specs['headings'].expected.trim())
  })
})
```

**Comment by wooorm** [comment]
Okay, so I’m using this code, `ex.js`:

```javascript
var fs = require('fs');
var unified = require('unified');
var reParse = require('remark-parse');
var remark2rehype = require('remark-rehype');
var rehypeStringify = require('rehype-stringify');

var doc = fs.readFileSync('ex.md', 'utf8');

var result = unified()
  .use(reParse)
  .use(remark2rehype)
  .use(rehypeStringify)
  .processSync(doc.replace(/·/g, ' '))
  .toString();

console.log(result);
```

If `ex.md` contains:

```markdown
(for convenience, · are replaced with
simple single spaces in the tests)

Header
------··

### H3···

H1··
=

H2
--··
```

...I’m getting (`node ex`):

```html
<p>(for convenience,   are replaced with
simple single spaces in the tests)</p>
<p>Header</p>
<hr>
<h3>H3</h3>
<h1>H1</h1>
<p>H2
--  </p>
```

Or, if `ex.md` contains:

```markdown
notATitle
- item 1
- item 2
```

...I’m getting (`node ex`):

```html
<p>notATitle</p>
<ul>
<li>item 1</li>
<li>item 2</li>
</ul>
```

Or, if `ex.md` contains:

```markdown
a|b
---|---
c|d
```

...I’m getting (`node ex`):

```html
<table>
<thead>
<tr>
<th>a</th>
<th>b</th>
</tr>
</thead>
<tbody>
<tr>
<td>c</td>
<td>d</td>
</tr>
</tbody>
</table>
```

Which basically looks like what should happen, right? Or not?
As steps forward: could you simplify [`__tests__/index.js`](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-heading-trailing-spaces/__tests__/index.js) so that it only has a minimal failing test case? And, could you tests on different OSes? I’m on macOS, and maybe this is Windows related?

**Comment by AmarOk1412** [comment]
...

sorry, it's me. Didn't read the good output. The result is correct here. It's my plugin.

Thank you!

**Comment by wooorm** [comment]
Ah, good, it was a weird issue!
Good luck with the plugin!
