### ISSUE TITLE
Remark stringify throws on list nested directly within a list

### ISSUE THREAD

**Issue by erquhart** [wooorm/remark#269]
Given the following html: `<ul><ul><li>test</li></ul></ul>`, remark-stringify errors out - the `bullet` param isn't defined when `listItem` is called. I'm assuming this means lists simply aren't expected to contain lists as direct descendants, but it would be nice to handle this gracefully, especially since rehype-remark is capable of generating the invalid mdast.

I have a live reproduction on Runkit, where you can also view the source mapped error:
https://runkit.com/erquhart/595544cb1cba570012811573

Also, here's a pretty-print of the MDAST that's causing the error:
https://gist.github.com/erquhart/72afed6fdf14fbf92f68d0f8ea163a88

I'm looking into it, but wondering if the problem is obvious to a maintainer.

**Comment by wooorm** [comment]
Hey @erquhart, thanks for the detailed report.
This is a problem because the tree is malformed (there’s a list directly in another list). That’s invalid, as there should always be a list-item between them. Thanks for finding it!

This is:
1. a bug in [`rehype-parse`](https://github.com/wooorm/rehype/tree/master/packages/rehype-parse)
1. not documented anywhere, and should probably be in [`mdast`](https://github.com/syntax-tree/mdast#list)
1. maybe there should be a useful error thrown in [`listItem()`](https://github.com/wooorm/remark/blob/f33df49d2968e0f2abaf74ec58d26dc3e6bd037d/packages/remark-stringify/lib/visitors/list-item.js#L46) if a non-list-item is given.

**Comment by erquhart** [comment]
It does seem to be documented in mdast, actually: https://github.com/syntax-tree/mdast#list

I'll close this and move it over to rehype-parse. Thanks!

**Comment by wooorm** [comment]
Yeah, I saw a note, but just made it a bit more explicit!

Don‘t worry, you can keep it open. It’s hard to keep track of all the repo’s, so I’ll just work on the others and close this from there!

**Comment by erquhart** [comment]
Okay, cool. Thanks :)

**Comment by wooorm** [comment]
I no longer think it’s a bug in `rehype-parse`, as it’s invalid HTML, the [spec states the below on the `<ul> element`](https://html.spec.whatwg.org/#the-ul-element):

> **Content model:**
>  Zero or more li and script-supporting elements.

...and the `<ul>` is neither `<li>` nor script-supporting.

What do you expect to happen on this invalid markup?

**Comment by erquhart** [comment]
It's tough because it works in browsers, and it occurs in popular tools like Paper from Dropbox. If you paste a nested list from paper into an editor with Remark parsing, it breaks. I wouldn't always expect valid html to be pasted.

**Comment by erquhart** [comment]
Perhaps either in rehype-remark or remark-stringify, list item nodes can be added where needed?

**Comment by erquhart** [comment]
Perhaps a plugin would work. Writing one seems simple enough, just need to check direct descendants of lists and wrap them. Would there be unexpected complexity, maybe related to positioning?

**Comment by wooorm** [comment]
Yeah I’m feeling this should be handled in [`hast-util-to-mdast`](https://github.com/syntax-tree/hast-util-to-mdast), but I’m just not entirely sure how to handle it.

Should all non-list-items be wrapped in a list-item?

**Comment by erquhart** [comment]
That would be awesome, and I can't think of a downside - any affected nodes would otherwise break on stringify.

**Comment by wooorm** [comment]
Fixed! You should be able to run `npm update` to pull in the latest [`hast-util-to-mdast`](https://github.com/syntax-tree/hast-util-to-mdast).

**Comment by erquhart** [comment]
Awesome, I'll try it now!
