### ISSUE TITLE
Nested lists without surrounding text lost in remark-rehype

### ISSUE THREAD

**Issue by erquhart** [wooorm/remark#270]
Stringifying this html to markdown:
```html
<ul>
  <li>
    <ul>
      <li>test</li>
    </ul>
  </li>
</ul>
```
**Expected**
Nested list item:
```markdown
  - test
```
**Actual**
Two bullets on list item:
```markdown
- - test
```

Then, if that markdown is parsed and stringified back to html through rehype, you get:
```html
<ul>
  <li><li>test</li></li>
</ul>
```

Runkit:
https://runkit.com/erquhart/59555f3a3798440012757a6c

**Comment by wooorm** [comment]
Interesting! Your last code is a bug! So now it’s in mdast-util-to-hast that doesn’t deal with non-paragraphs in list-items.

However, expected and actual is not a bug, [that’s what I just proposed in #269](https://github.com/wooorm/remark/issues/269#issuecomment-312077618). Again, your input HTML is “invalid” according to the HTML spec. There’s no way to handle that invalid HTML, transform it to markdown (proper markdown, which I just added), back to HTML, and expect it to still be “broken”!

The actual HTML output should, in my opinion be:

```html
<ul>
  <li>
     <ul>
       <li>test</li>
     </ul>
  </li>
</ul>
```

What do you expect?

**Comment by erquhart** [comment]
The input html is valid:

```html
<ul>
  <li>
    <ul>
      <li>test</li>
    </ul>
  </li>
</ul>
```

**Comment by wooorm** [comment]
Oh, I misread your input HTML, I though it was still the HTML from the previous issue, sorry.

As your HTML has two list-items, why do you expect one bullet?

**Comment by erquhart** [comment]
The two bullets aren't a problem necessarily, but it doesn't translate back through to html.

If I put that html through rehype and remark to markdown, then take the resulting markdown and put it back through to html through to rehype, the inner `ul` element is lost in the process.

**Comment by erquhart** [comment]
So in other words:

Rehype input:
```html
<ul><li><ul><li>test</li></ul></li></ul>
```

Remark output:
```markdown
- - test
```

Remark input (same as previous Remark output):
```markdown
- - test
```

Rehype output:
```html
<ul><li><li>test</li></li></ul>
```

What browsers (or Chrome, at least) do with that:
```html
<ul><li></li><li>test</li></ul>
```

**Comment by wooorm** [comment]
Oh, yeah, that’s an issue and I’m working on, but from the issues subject line I thought you didn’t expect the two bullets.

**Comment by erquhart** [comment]
That was my thought at first, but it does seem that two bullets is accurate according to the only worthwhile spec out there: http://spec.commonmark.org/0.26/#example-259

Title updated.

**Comment by wooorm** [comment]
Alright! :+1:

**Comment by wooorm** [comment]
Fixed and released!

**Comment by erquhart** [comment]
You, sir, are the man.

**Comment by wooorm** [comment]
Ha, thanks 😛
