### ISSUE TITLE
Nest invalidly nested lists within previous sibling list item when possible

### ISSUE THREAD

**Issue by erquhart** [wooorm/remark#272]
What do you think about including unwrapped, directly nested lists in previous sibling list items when they're available? I think this follows wrapping unwrapped non-list items as expected behavior, and it can be reliably transformed back and forth between markdown and html.

**Given the following input:**
```html
<ul>
  <li>item one</li>
  <ul><li>nested item</li></ul>
</ul>
```
**Current output:**
```html
<ul>
  <li>item one</li>
  <li><ul><li>nested item</li></ul></li>
</ul>
```
```markdown
- item one
- - nested item
```

**Ideal output:**
```html
<ul>
  <li>item one
    <ul><li>nested item</li></ul>
  </li>
</ul>
```
```markdown
- item one
  - nested item
```

**Comment by wooorm** [comment]
Hey @erquhart, I get your problem but I don’t think it should be in either of the related projects.
Instead, you should probably create a [**rehype**](https://github.com/wooorm/rehype) plugin that does this!

The previous problem, where an error was thrown, was indeed a bug, and that’s fixed now, but this seems like something that not everyone wants!

**Comment by erquhart** [comment]
Makes sense - thanks :)
