### ISSUE TITLE
Inline elements from rehype become block elements in remark

### ISSUE THREAD

**Issue by erquhart** [wooorm/remark#273]
When inline elements aren't wrapped in a block element, each inline element is treated as a block element.

Example:

```js
const html = 'plain <strong>strong</strong> <em>em</em> <b>bold</b> <s>strikethrough</s>';

unified()
  .use(htmlToRehype)
  .use(rehypeToRemark)
  .use(remarkToMarkdown)
  .processSync(html)
  .contents;
```

Output:
```markdown
plain \n\n**strong**\n\n \n\n_em_\n\n \n\n**bold**\n\n \n\n~~strikethrough~~\n
```

Here's a live repro on Runkit: https://runkit.com/erquhart/595ab7fa5002520012e72173

**Comment by wooorm** [comment]
Fixed! you should be able to run `npm update` and see it fixed. See the linked commits above for more info.

**Comment by erquhart** [comment]
Thank you!
