### ISSUE TITLE
HTML with adjacent marks fails remark parsing

### ISSUE THREAD

**Issue by erquhart** [wooorm/remark#274]
Example:

```js
const html = '<p><strong>a</strong><strong>b</strong></p>';

const markdown = unified()
  .use(htmlToRehype)
  .use(rehypeToRemark)
  .use(remarkToMarkdown)
  .processSync(html)
  .contents;
  
unified()
  .use(markdownToRemark)
  .use(remarkToRehype)
  .use(rehypeToHtml)
  .processSync(markdown)
  .contents;
```

Output:
```html
<p><strong>a**</strong>b**</p>
```

Runkit link: https://runkit.com/erquhart/595ac0ba97404100128e2aa1

The base issue is that remark can't properly parse this: `**a****b**`, and the above test is a legitimate path where this kind of markdown can be output through Unified.

**Comment by wooorm** [comment]
What do you expect to happen? Markdown does not support adjacent `strong` nodes, so there’s no way to keep them both in.

**Comment by erquhart** [comment]
Ah, wasn't aware it's invalid. Not much to do then - thanks :)
