### ISSUE TITLE
Inline html tag content is trimmed

### ISSUE THREAD

**Issue by erquhart** [wooorm/remark#275]
The contents of inline tags are being trimmed. When parsing html to markdown:

**Input**
```
a b<span> </span>c d</span><strong> e</strong>
```

**Expected output**
```
a b c d **e**
```

**Actual output**
```
a bc d**e**
```

Runkit repro: https://runkit.com/erquhart/595d36c4e60f6b0012c00405

**Comment by wooorm** [comment]
This is an issue with [`rehype-minify-whitespace`](https://github.com/wooorm/rehype-minify/tree/master/packages/rehype-minify-whitespace). Could you open an issue over there?

**Comment by erquhart** [comment]
No problem!

**Comment by wooorm** [comment]
Thanks!
