### ISSUE TITLE
remark will change the jeky settings.

### ISSUE THREAD

**Issue by wsdjeg** [wooorm/remark#281]
I have a markdown file:
```markdown
---
title: "SpaceVim lang#java layer"
---

# [SpaceVim Layers:](https://spacevim.org/layers) lang#java
```
which I hope the title only shown in the top of the browser, but remark will change it to:

```
* * *

## title: "SpaceVim lang#java layer"

# [SpaceVim Layers:](https://spacevim.org/layers) lang#java


```

**Comment by wooorm** [comment]
Use a [plugin](https://github.com/wooorm/remark/blob/master/doc/plugins.md#list-of-plugins): [`remark-frontmatter`](https://github.com/wooorm/remark-frontmatter).

**Comment by wsdjeg** [comment]
@wooorm sorry, I can not understand how to use the frontmatter in cli. I use [neoformat](https://github.com/sbdchd/neoformat) in vim. and the default command is 
```
function! neoformat#formatters#markdown#remark() abort
    return {
            \ 'exe': 'remark',
            \ 'args': ['--no-color', '--silent'],
            \ 'stdin': 1,
            \ }
endfunction
```

**Comment by wsdjeg** [comment]
I think I should change it to 
```
function! neoformat#formatters#markdown#remark() abort
    return {
            \ 'exe': 'remark',
            \ 'args': ['--no-color', '--silent', '--use', 'remark-frontmatter
'],
            \ 'stdin': 1,
            \ }
endfunction
```

**Comment by wooorm** [comment]
Correct, but you have to install the plugin with npm.

Also, the [getting started](https://github.com/wooorm/remark/blob/master/doc/getting-started.md#using-remark-in-a-project) guide comes with some examples on how to use the CLI.

Note that this issue tracker is for questions and issues with remark, not for projects like neoformat and how to use remark in it. neoformat has [its own issue tracker](https://github.com/sbdchd/neoformat)!
