### ISSUE TITLE
Image with parens in url parsed as ImageReference

### ISSUE THREAD

**Issue by erquhart** [wooorm/remark#282]
Images with parentheses in the name are common, but result in a mis-parse:

**Markdown:**
```markdown
![test](/path/to/image (1).jpg)
```

**Expected:**
```markdown
{
  type: 'paragraph',
  children: [
    { type: 'image', alt: 'test', url: 'url' }
  ]
}
```

**Actual:**
```md
{
  type: 'paragraph',
  children: [
    { type: 'imageReference', referenceType: 'shortcut', alt: 'test', identifier: 'test' },
    { type: 'text', value: '(/path/to/image(1).jpg)' }
  ]
}
```

**Runkit:**
https://runkit.com/erquhart/597a5df7a3c36b00121d19f2

**Comment by wooorm** [comment]
Doesn’t work in other markdown vendors, like here:

```markdown
![test](/path/to/image (1).jpg)
```

Yields:

![test](/path/to/image (1).jpg)

So this is expected behaviour?

**Comment by wooorm** [comment]
P.S. it’s about the space:

```markdown
![test](/path/to/image%20(1).jpg)
```

Yields:

![test](/path/to/image%20(1).jpg)

**Comment by erquhart** [comment]
Dude you are sooo fast! Yeah, I was just realizing that, looks like we need to encode.

**Comment by wooorm** [comment]
If you generate the markdown, then that’s indeed what you need to do! Or, create a PR that updates `rehype-stringify` to encode stuff when needed (if it doesn’t already?)

**Comment by zwz** [comment]
I also came across this issue with image file name containing a space.
Seems `rehype-stringify` has not fixed it yet.

**Comment by zwz** [comment]
But at second thought, maybe it is still a bug of remark itself
As @erquhart reports, the image (whose filename contains space) is parsed as an `imageReference` instead of `image`. 
And the output of rehype-stringify is something like this
```
<p>![caption for the image](img/Untitled 3.jpg)</p>
```

It should be something `<img src=....>` if it were parsed as an `image`.

**Comment by burgessa23** [comment]
I'm also seeing issues parsing images with spaces in the filename `![](relative/path/to/file name.png)` bails out here: https://github.com/remarkjs/remark/blob/master/packages/remark-parse/lib/tokenize/link.js#L346 in my case `value.charAt(index)` is `n`, the first char after the space in the filename

**Comment by wooorm** [comment]
It should not become an image. Because there is a space in the path. This is how markdown works. 
If you want spaces, encode them (`%20`) or wrap the destination in angle brackets `<relative/path/to/file name.png>`.
