### ISSUE TITLE
Plugin idea: strip unreferenced definitions

### ISSUE THREAD

**Issue by niftylettuce** [wooorm/remark#285]
Might be nice to have some sort of `pre-publish` type package for `remark` where it strips off defined links that are unused.

Does this already exist?

**Comment by wooorm** [comment]
Hi @niftylettuce! :wave:

Sounds like a good idea. I don’t think it exists yet though.
Would you be interested in creating this?

**Comment by niftylettuce** [comment]
Call it `remark-strip-unused-links`?

**Comment by wooorm** [comment]
'remark-strip-unused-definitions' makes more sense to me (links are the things in text that show up clickable, and definitions can be used for images too)

**Comment by wooorm** [comment]
Or 'remark-strip-unreferenced-definitions' (slightly more apt)

**Comment by niftylettuce** [comment]
whatever you think is best! you're the mastermind behind remark 😆  ... but I have very limited time the next weeks so if you were hoping I could get my hands in here on this I apologize in advance 😹

**Comment by wooorm** [comment]
That's fine, take all the time you want!

PS I don't have time to make your plugins either. I can provide guidance tho.

**Comment by wooorm** [comment]
See https://github.com/wooorm/remark/issues/291#issuecomment-332175585.
