### ISSUE TITLE
Plugin idea: auto add “Install” blocks with installation instructions

### ISSUE THREAD

**Issue by niftylettuce** [wooorm/remark#286]

**Comment by wooorm** [comment]
:wave:

Good idea. Would you be interested in creating this?

**Comment by niftylettuce** [comment]
I think it should look like this:

<img width="860" alt="screen shot 2017-08-19 at 6 57 10 pm" src="https://user-images.githubusercontent.com/523141/29490640-40605392-8510-11e7-97f7-e2248c8ebcd7.png">

Maybe we can have it give defaults, and be configurable with some sort of template like `example.js` has for https://github.com/wooorm/remark-usage.  Maybe call this package `remark-install`.

**Comment by niftylettuce** [comment]
Obviously if it didn't have any content in a template then it'd sniff for the `# Install` or `# Installation` headers and then inject it just like `remark-usage` does.

**Comment by niftylettuce** [comment]
Perhaps we use `install.js` if it exists (and it gets rendered like <https://github.com/wooorm/remark-usage>).  If there is no such file then it includes default npm and yarn blocks like above (but without the extra fluff I had there).

**Comment by wooorm** [comment]
I don’t think `.js` will work, as `## install` is almost always done in a shell (such as bash).

I actually think most often you don’t need a file: just `name` in `package.json`.

Some things to note: 
1. some people prefer `npm install remark`, some `npm install --save remark` (but now npm by default autosaves dependencies).
1. Some stuff is almost always a dev-dependency: `npm install --save-dev remark`.
1. Some stuff (maybe if there’s a `bin` in `package.json`?) should sometimes be global: `npm install --global remark-cli`

**Comment by wooorm** [comment]
I think you can detect yarn, through a `yarn.lock`, and only include that block if it’s there.

**Comment by wooorm** [comment]
See https://github.com/wooorm/remark/issues/291#issuecomment-332175585.
