### ISSUE TITLE
Plugin idea: Add global default bookmarks and automatic parsing

### ISSUE THREAD

**Issue by niftylettuce** [wooorm/remark#287]
Similar to a plugin like Octolinker <https://chrome.google.com/webstore/detail/octolinker/jlmafbaeoofdegohdhinkhilhclaklkp?hl=en>, we should automatically parse links like `[koa][]` and make sure they get a set default when rendered to the GitHub package if found or NPM package if not found.  Possibly could use <https://github.com/ben-eb/remark-bookmarks> to start with somehow.  Maybe this can get added to your <https://github.com/wooorm/remark-preset-wooorm>.

**Comment by wooorm** [comment]
How about links like `[Some text][npm:koa]`, `[Other text][gh:koajs/koa]`, etc?
Then the plugin could just add definitions at the end of the file for those, respectively `[npm:koa]: https://www.npmjs.com/package/koa` and `[gh:koajs/koa]: https://github.com/koajs/koa`?

**Comment by niftylettuce** [comment]
That'd be dope!

**Comment by niftylettuce** [comment]
Maybe we call this `remark-global-bookmarks`?

Then others could do things like `[pip:foobar]` or `[gem:foobar]` down the road.

**Comment by wooorm** [comment]
1. Do you mean other packages would provide the pip or gem thing?
2. I'd say that this project would add definitions for references with know 'protocols' when they are used, and remove definitions with those prefixes if they aren't referenced
3. Not sure about the name, remark-autodefine?
4. Maybe you could somehow get values for package.json too ('pkg:author', 'pkg:author.url'?)

**Comment by niftylettuce** [comment]
1. No, I was just suggesting it 👍 
2. I agree
3. `remark-automatic-link-definitions` maybe?  idk, something good with keywords?  I guess it'd be cool to add this to your preset too once it's done 👏 
4. That would be awesome.

**Comment by wooorm** [comment]
See https://github.com/wooorm/remark/issues/291#issuecomment-332175585.
