### ISSUE TITLE
Should we mention the most popular remark presets somewhere?

### ISSUE THREAD

**Issue by niftylettuce** [wooorm/remark#289]
Link to most popular presets on NPM?

<https://www.npmjs.com/search?q=remark-preset>

Maybe include this in docs?

**Comment by wooorm** [comment]
Yeah sure! Want to set this up? I’d say under [“List of Plugins”](https://github.com/wooorm/remark/blob/master/doc/plugins.md#table-of-contents), add a “List of Presets”?

**Comment by wooorm** [comment]
I’d say only add stuff that’s recently maintained though!

**Comment by niftylettuce** [comment]
Done
