### ISSUE TITLE
generate mdast from markdown string without using a processor

### ISSUE THREAD

**Issue by Sewdn** [wooorm/remark#296]
Probably a very simple answer, but I cant seem to figure out how to parse markdown to an mdast tree.
in mdast@3.0.0 you could easily do this:

```
mdast.parse('# test');
```

After refactoring to remark, with remark-parse and remark-stringify, using the unified interface, I cant seem to parse a markdown string to an mdast tree without using a processor.

Documentation states you could [access the parser](https://github.com/wooorm/remark/tree/master/packages/remark-parse#parseparser), but it's not documented how to use this parser to create an MDAST from a markdowm string. The Parser should always receive a markdown string and a vFile instance. Does this vFile need to be created first?

I would expect something like this would be possible:

```
const markdown = require('remark-parse');
var tree = markdown.Parser().parse('# test');
```

**Comment by wooorm** [comment]
If you have a processor, you can parse like this:

```js
var processor = unified().use(parse).use(stringify)
var tree = processor.parse('# test')
```

I think you can use `remark-parse` directly like so, but it’s not recommended:

```js
var Parser = new require('remark-parse').Parser
var parser = new Parser
var tree = parser.parse('# test')
```

**Comment by Sewdn** [comment]
Thanks for your swift reply! Constructing the parser does the trick. Thanks!

I need this mdast construction directly, because I want to parse the contents of a codeBlock with language markdown to an mdast and inject this in the tree (replacing the codeblock)

**Comment by wooorm** [comment]
Oh yeah that’s a good case! Good luck 😉

**Comment by Sewdn** [comment]
It seems that using remark-parse directly, is still not working.

``` javascript
const markdown = require('remark-parse');
var Parser = markdown.Parser;
var parser = new Parser();
var tree = parser.parse('# test');
console.log(tree.children[0]);
```

yields

``` json
{ type: 'paragraph',
   children: [ { type: 'text', value: 'undefined', position: [Object] } ],
   position: 
    Position {
      start: { line: 1, column: 1, offset: 0 },
      end: { line: 1, column: 10, offset: 9 },
      indent: [] } }
```

**Comment by wooorm** [comment]
Ahh, you must pass in the [`doc` and a `file`](https://github.com/wooorm/remark/blob/21a16d57d60a78eba04861fe6b7835e655244290/packages/remark-parse/lib/parser.js#L12) to the constructor. In this parser, you can omit the `doc`, but must pass a `file` as the second param.

I’ll update the above example!
