### ISSUE TITLE
Give option for query params not to be encoded

### ISSUE THREAD

**Issue by yangshun** [wooorm/remark#302]
React docs site was migrated from Jekyll to Gatsby (which uses remark) and the rendered GitHub links were different (and broken as a result).

```js
var remark = require('remark');
var html = require('remark-html');

const string = 'This [link](https://github.com/facebook/react/pulls?q=is%3Apr%20is%3Aclosed) is double encoded.';

remark()
  .use(html)
  .process(string, function (err, file) {
    console.log(String(file));
  });
```

Results in a generated output with the query params being encoded again. This causes the links to be double encoded (notice that the `%` has been converted into a `%25`.

**Output**

```
<p>This <a href="https://github.com/facebook/react/pulls?q=is%253Apr%20is%253Aclosed">link</a> is double encoded.</p>
```

- Expected: [https://github.com/facebook/react/pulls?q=is%3Apr%20is%3Aclosed](https://github.com/facebook/react/pulls?q=is%3Apr%20is%3Aclosed)

- Actual: [https://github.com/facebook/react/pulls?q=is%253Apr%20is%253Aclosed](https://github.com/facebook/react/pulls?q=is%253Apr%20is%253Aclosed) 

Is this behavior intended? If it is, it'll be nice to provide an option not to encode the query params in links.

I'm not sure whether this is an issue of `remark` or `remark-html`. If this issue should be filed in  `remark-html` instead I'll be glad to shift it over.

Related issue: https://github.com/facebook/react/pull/11066

**Comment by wooorm** [comment]
@yangshun Thanks for the detailed issue, and for tracking it down to us here! And welcome :)

This is indeed a bug, in a utility deep down. The above commit fixes it, and I’ll publish a patch when Travis turns green.

I’m not sure if your version of Gatsby uses the latest major of remark-html? If that’s the case, the patch should be pulled in automatically on new semver-supporting npm installs!

**Comment by yangshun** [comment]
That was an amazingly fast response! Thank you so much! 😄

**Comment by wooorm** [comment]
Published! This should work now! :)
