### ISSUE TITLE
Emphasis and strong  should use marker identical with the input marker

### ISSUE THREAD

**Issue by marfuzzi** [wooorm/remark#303]
**Input markdown:**
`Emphasis  with *asterisks* or _underscores_. ` 
`Strong with **asterisks** and __underscores__.`

**Use `remark-parse`**
Parse markdown to a syntax tree.

**Use `remark-stringify`**
Stringify syntax trees to markdown.

**Actual markdown:**
`Emphasis  with _asterisks_ or _underscores_. `     (markers to use for emphasis(default  '_'))
`Strong with **asterisks** and **underscores**.` ( markers to use for strong(default  '*'))

**Expected markdown:**
`Emphasis  with *asterisks* or _underscores_. `    
`Strong with **asterisks** and __underscores__.`

I expect emphasis and strong  should use marker identical with the input marker.
I’m not sure how to do it.
I think the only way to fix this is by rewriting `function escape` or `function setOptions`

**Comment by wooorm** [comment]
@marfuzzi Hi! 👋 Nice to meet you and welcome to remark.

remark formats markdown: think of it as prettier. You can pass it options for syntax, use plugins to check syntax and content, or use plugins to generate content.

I don’t think we should do this.

Related to GH-132.
