### ISSUE TITLE
Clarify the remark-stringify Compiler extension example

### ISSUE THREAD

**Issue by Graham42** [wooorm/remark#304]
I'm a bit confused by the example given for how to extend to compiler for remark-stringify https://github.com/wooorm/remark/tree/master/packages/remark-stringify#extending-the-compiler

Can we avoid reusing the variable/function name `heading`? I feel like would make this much clearer.

```javascript
module.exports = gap;

function gap() {
  var Compiler = this.Compiler;
  var visitors = Compiler.prototype.visitors;
  var heading = visitors.heading;

  visitors.heading = heading;

  function heading(node) {
    return (node.depth === 2 ? '\n' : '') + heading.apply(this, arguments);
  }
}
```

**Comment by wooorm** [comment]
Ohh yes, that’s a bug! Should be something like this:

```diff
module.exports = gap;

function gap() {
  var Compiler = this.Compiler;
  var visitors = Compiler.prototype.visitors;
- var heading = visitors.heading;
+ var original = visitors.heading;

  visitors.heading = heading;

  function heading(node) {
-   return (node.depth === 2 ? '\n' : '') + heading.apply(this, arguments);
+   return (node.depth === 2 ? '\n' : '') + original.apply(this, arguments);
  }
}
```

...right?

Would you like to create a PR for this? :)

**Comment by Graham42** [comment]
Sure thing. Thanks for the clarification.

**Comment by atian25** [comment]
@wooorm I'm confused with how to use this `gap`? how to attach it to remark? any fixtures or example?

**Comment by wooorm** [comment]
This is a bit of an old issue so if you have further questions please ask them on spectrum , or if it's an issue, raise a new one!
