### ISSUE TITLE
Ignored files errors not suppressed

### ISSUE THREAD

**Issue by niftylettuce** [wooorm/remark#309]
```sh
λ ~/Public/lad/ master* remark template/test/web/snapshots/index.js.md -qf
template/test/web/snapshots/index.js.md
  1:1  error  Cannot process specified file: it’s ignored

✖ 1 error
```

contents of `.remarkignore`:

```
template/test/web/snapshots/index.js.md
```

I'd imagine instead the CLI should not throw an error and simply ONLY output the warning if `-q` is not passed

**Comment by wooorm** [comment]
Ahh, missed this in the `unified-args` update. `unified-engine` has a [`silentlyIgnore`](https://github.com/unifiedjs/unified-engine/blob/master/doc/options.md#optionssilentlyignore) option but that isn‘t available in `unified-args`.

Could you open an issue there? And potentially: a PR? 🎉
