### ISSUE TITLE
Remark in the browser / React native 

### ISSUE THREAD

**Issue by MrLoh** [wooorm/remark#310]
I’d love to use remark in my React Native app to display markdown in a customized way. Unfortunately it can’t be use because remark requires some node dependencies (fs). Anything node specific seems to be optional for some APIs though, any chance for a browser version?

**Comment by Rokt33r** [comment]
Did you check https://github.com/mapbox/remark-react?

**Comment by wooorm** [comment]
There are a bunch of cases where remark and the ecosystem run in the browser, so I’m guessing it’s related to your build steps or React Native.

What is it you’re trying to do?

**Comment by wooorm** [comment]
Should work! 🤷‍♂️

**Comment by MrLoh** [comment]
If I import it, I get an error, because it tries to import `path` module from node, very hard to track down which of the dependencies is throwing that. How would you use remark in the browser, when you don't use npm? Maybe I could just include a minified executable in my code.

**Comment by wooorm** [comment]
Most people do that with tools such as webpack or rollup, I personally like browserify a lot!

**Comment by MrLoh** [comment]
Yeah of course I know those tools. I usually use webpack. The problem ist that non installing the package and importing it in react native fails, because it is considered node. Probably some dependency has a different setup for node and the browser (I think you can declare that in the package.jaon somehow or maybe they check wether the window object exists) and then it assumes that everything that is not a browser environment is a node environment, which is very false in the case of React native, which is a strange js environment with only the features that are available both in the browser and in node. It must be one of unities dependencies, but I guess there’s no easy way to fix it, without forking a bunch of dependencies.
