### ISSUE TITLE
Insert elements in AST of a file

### ISSUE THREAD

**Issue by grmpyninja** [wooorm/remark#312]
Could you provide an example how to parse and insert elements into markdown's AST? Can it be done in-place or do I need to monitor a file and replace the whole content to write it back? I would like to write a tool to build documents based on params or partial texts, but no idea how to do it in JavaScript + remark.

simple example: I'd like to have a template where for instance there will be a header and I'd like to find a list under a `header-level-1` with value `TODO` and if there is a list, append a new element to it

*document.md*

```
# TODO

- buy milk
```
e.g. pseudo xpath (I wrote it long time ago) to get a handler to:
```
list = h1[@text="TODO"]/list
```

so I can do a simple action like

```
list.append("text")
```
I guess text should be some kind of an AST element and then how to dump a new content to a file? Is it possible to do it in-place?

**Comment by wooorm** [comment]
The [section on creating plugins](https://github.com/wooorm/remark/blob/master/doc/plugins.md#creating-plugins) will probably provide enough inspiration for you to create something like that.

For the selecting part, [`unist-util-select`](https://github.com/eush77/unist-util-select) may be of interest?

More general questions can go on Gitter btw, there’s more of a community there to answer your questions!
