### ISSUE TITLE
Add `style` properties on nodes

### ISSUE THREAD

**Issue by wooorm** [wooorm/remark#32]
Currently, only global stringification settings, such as `bullet`, are supported. I’d like to extend stringification style to per-node settings. Thus, a list-item can have a `style.bullet = ‘*'` property.

Something like:

*   `heading` nodes have an enum `headingStyle` property set to `"atx"`,
    `"atx-closed"`, or `"setext"`;
*   `tables` nodes have a boolean `looseTable` property;
*   `tables` nodes have a boolean `spacedTable` property;
*   `code` nodes have a nullable enum `fenceMarker` property set to ``"`"`` or
    `"~"`;
*   `code` nodes have a boolean `fences` property;
*   `listItem` nodes have an enum `listItemBullet` property set to `*`, `-`,
    `+`, `.`, or `)`.
*   `listItem` nodes have a nullable `listItemIndex` property set to an integer;
*   `horizontalRule` nodes have an enum `ruleMarker` property set to `*`, `-`, or
    `_`.
*   `horizontalRule` nodes have a boolean `ruleRepetition` property;
*   `horizontalRule` nodes have a boolean `ruleSpaces` property;
*   `strong` and `emphasis` nodes have an enum `emphasisMarker` property
    set to `_` or `*`.

These should be overwritten when a setting is given to **mdast** (this allows
**mdast** to fix code-style), but overwrite the default values noted in
[`mdast.process()`](https://github.com/wooorm/mdast#mdastprocessvalue-options-done)

Supersedes GH-30.

**Comment by retorquere** [comment]
I like your reasoning in #30. I should perhaps not want mdast to behave differently - although that implicitly enforces a certain style guide, this is perhaps something one can get used to to get the benefit of semantically-roundtrippable markdown processing.

**Comment by wooorm** [comment]
Closed in favour of GH-132.
