### ISSUE TITLE
Entity nodes

### ISSUE THREAD

**Issue by wooorm** [wooorm/remark#66]
Entities are handled pretty simply by mdast: they are (all) removed.

However, removing those loses a lot of information. For example, it makes figuring out the position of something a lot harder, as can be seen by this [bug](https://github.com/wooorm/atom-linter-alex/issues/4#issuecomment-141568295) in [alex](https://github.com/wooorm/alex), which also exists in other tools trying to figure out the original location of something inside a `text` node.

By adding `entity` nodes, this problem can be mitigated. Most importantly it ensures that entities can be recompiled in the output of **mdast**.

I’m proposing (I’m not sure yet), something like the following IDL:

```idl
interface Entity <: Text {
    type: "entity";
    name: string | number;
    value: string;
}
```

When `name` is `number`, it’ll be compiled ass `$#name;`, when `string`, as `$name;`

For example, the following entity:

```md
This &amp that <!-- yes, the closing semicolon is missing, HTML accepts that...-->
```

Yields:

```json
{
  "type": "entity",
  "name": "amp",
  "value": "&"
}
```

And, the following entity:

```md
etc&#8230;
```

Yields:

```json
{
  "type": "entity",
  "name": 8230,
  "value": "…"
}
```

In fact, this interface would work exactly like the mdast escape node for tools accessing the value of something using `mdast-util-to-string`, but it has the added benefit of breaking `text` nodes where the position in the original document is offset.

**Comment by eush77** [comment]
Isn't retaining positional information achievable by splitting one text node into several adjacent text nodes?

```json
{
  "type": "paragraph",
  "children": [
    {
      "type": "text",
      "value": "this ",
      "position": {
        "start": {
          "line": 1,
          "column": 1
        },
        "end": {
          "line": 1,
          "column": 6
        }
      }
    },
    {
      "type": "text",
      "value": "&",
      "position": {
        "start": {
          "line": 1,
          "column": 6
        },
        "end": {
          "line": 1,
          "column": 11
        }
      }
    },
    {
      "type": "text",
      "value": " that",
      "position": {
        "start": {
          "line": 1,
          "column": 11
        },
        "end": {
          "line": 1,
          "column": 16
        }
      }
    }
  ],
  "position": {
    "start": {
      "line": 1,
      "column": 1
    },
    "end": {
      "line": 1,
      "column": 16
    }
  }
}
```

Deviations from [Commonmark](http://spec.commonmark.org/0.22/#entities) are not the best thing in the world.

**Comment by wooorm** [comment]
@eush77 Oh that’s also possible! Nice catch! :smiley: 

That would certainly help in “less” type of nodes in the mdast AST, but would disable programmatic addition / removal of select (v.s. the current support for “all”) entities.

The latter of course being not the original reason for these entity nodes, but still... nice?

It’s also related to GH-32, whose goal is to ensure input and output to be more similar: often users don’t encode all non-ASCII characters as entities, just some.

**Comment by eush77** [comment]
> That would certainly help in “less” type of nodes in the mdast AST, but would disable programmatic addition / removal of select (v.s. the current support for “all”) entities.

Sorry, I didn't quite understand. Did you mean addition/removal of text selection that spans across multiple adjacent text nodes?

**Comment by wooorm** [comment]
> > That would certainly help in “less” type of nodes in the mdast AST, but would disable programmatic addition / removal of select (v.s. the current support for “all”) entities.

> Sorry, I didn't quite understand. Did you mean addition/removal of text selection that spans across multiple adjacent text nodes?

No, I meant that the current entity options are an “all or nothing” approach, having `entity` nodes would mean that some entities would be re-encoded whereas others would be their normal utf-8 character:

So, with nodes, the following could be re-compiled exactly:

```md
foo & AT&amp;T
```

**Comment by wooorm** [comment]
@eush77 I’m close to done with an entity decoder with support for emitting nodes (whether `text` or `entity` for entities), positions, triggering warnings. That should be used by both `mdast` and `hast`.

I think I’m preferring `text` nodes as a replacement for both `entities` and `escape`, and different adjacent text nodes for gaps in positioning

E.g.,

```js
[ { type: 'text',
       value: 'I\'m ',
       position: { start: { line: 1, column: 1 }, end: { line: 1, column: 5 } } },
     { type: 'text',
       value: '¬',
       position: { start: { line: 1, column: 5 }, end: { line: 1, column: 9 } } },
     { type: 'text',
       value: 'it; I tell you.\n\nI\'m ',
       position: { start: { line: 1, column: 9 }, end: { line: 3, column: 5 } } },
     { type: 'text',
       value: '∉',
       position: { start: { line: 3, column: 5 }, end: { line: 3, column: 12 } } },
     { type: 'text',
       value: ' I tell you.\n\n&#x.\n',
       position: { start: { line: 3, column: 12 }, end: { line: 6, column: 1 } } } ]
```

...for:

```txt
I'm &notit; I tell you.

I'm &notin; I tell you.

&#x.
```

With some warnings:

```javascript
[ { message: 'Named character references must be known',
       position: { line: 1, column: 5 } },
     { message: 'Numeric character references cannot be empty',
       position: { line: 5, column: 4 } } ]
```

**Comment by eush77** [comment]
Great!

**Comment by wooorm** [comment]
@eush77 Well, yesterday I had this fixed, but I lost my code so it’ll be delayed ± 2-3 more days :/

**Comment by wooorm** [comment]
Well, that turned out to be months. Anyway, somewhere this week in 3.0.0.
